package net.craftlin.bukkit.impl.value

import net.craftlin.api.util.value.EnumValue
import net.craftlin.api.value.BlockType
import org.bukkit.Material

object BukkitBlockType: EnumValue<BlockType, Material>(BlockType::class) {
    override fun convert(api: BlockType): Material {
        return when(api) {
            //<editor-fold desc="Blocks">
            BlockType.ACACIA_BUTTON -> Material.ACACIA_BUTTON
            BlockType.ACACIA_DOOR -> Material.ACACIA_DOOR
            BlockType.ACACIA_FENCE -> Material.ACACIA_FENCE
            BlockType.ACACIA_FENCE_GATE -> Material.ACACIA_FENCE_GATE
            BlockType.ACACIA_LEAVES -> Material.ACACIA_LEAVES
            BlockType.ACACIA_LOG -> Material.ACACIA_LOG
            BlockType.ACACIA_PLANKS -> Material.ACACIA_PLANKS
            BlockType.ACACIA_PRESSURE_PLATE -> Material.ACACIA_PRESSURE_PLATE
            BlockType.ACACIA_SAPLING -> Material.ACACIA_SAPLING
            BlockType.ACACIA_SLAB -> Material.ACACIA_SLAB
            BlockType.ACACIA_STAIRS -> Material.ACACIA_STAIRS
            BlockType.ACACIA_TRAPDOOR -> Material.ACACIA_TRAPDOOR
            BlockType.ACACIA_WOOD -> Material.ACACIA_WOOD
            BlockType.ACTIVATOR_RAIL -> Material.ACTIVATOR_RAIL
            BlockType.AIR -> Material.AIR
            BlockType.ALLIUM -> Material.ALLIUM
            BlockType.ANDESITE -> Material.ANDESITE
            BlockType.ANVIL -> Material.ANVIL
            BlockType.ATTACHED_MELON_STEM -> Material.ATTACHED_MELON_STEM
            BlockType.ATTACHED_PUMPKIN_STEM -> Material.ATTACHED_PUMPKIN_STEM
            BlockType.AZURE_BLUET -> Material.AZURE_BLUET
            BlockType.BARRIER -> Material.BARRIER
            BlockType.BEACON -> Material.BEACON
            BlockType.BEDROCK -> Material.BEDROCK
            BlockType.BEETROOTS -> Material.BEETROOTS
            BlockType.BIRCH_BUTTON -> Material.BIRCH_BUTTON
            BlockType.BIRCH_DOOR -> Material.BIRCH_DOOR
            BlockType.BIRCH_FENCE -> Material.BIRCH_FENCE
            BlockType.BIRCH_FENCE_GATE -> Material.BIRCH_FENCE_GATE
            BlockType.BIRCH_LEAVES -> Material.BIRCH_LEAVES
            BlockType.BIRCH_LOG -> Material.BIRCH_LOG
            BlockType.BIRCH_PLANKS -> Material.BIRCH_PLANKS
            BlockType.BIRCH_PRESSURE_PLATE -> Material.BIRCH_PRESSURE_PLATE
            BlockType.BIRCH_SAPLING -> Material.BIRCH_SAPLING
            BlockType.BIRCH_SLAB -> Material.BIRCH_SLAB
            BlockType.BIRCH_STAIRS -> Material.BIRCH_STAIRS
            BlockType.BIRCH_TRAPDOOR -> Material.BIRCH_TRAPDOOR
            BlockType.BIRCH_WOOD -> Material.BIRCH_WOOD
            BlockType.BLACK_BANNER -> Material.BLACK_BANNER
            BlockType.BLACK_BED -> Material.BLACK_BED
            BlockType.BLACK_CARPET -> Material.BLACK_CARPET
            BlockType.BLACK_CONCRETE -> Material.BLACK_CONCRETE
            BlockType.BLACK_CONCRETE_POWDER -> Material.BLACK_CONCRETE_POWDER
            BlockType.BLACK_GLAZED_TERRACOTTA -> Material.BLACK_GLAZED_TERRACOTTA
            BlockType.BLACK_SHULKER_BOX -> Material.BLACK_SHULKER_BOX
            BlockType.BLACK_STAINED_GLASS -> Material.BLACK_STAINED_GLASS
            BlockType.BLACK_STAINED_GLASS_PANE -> Material.BLACK_STAINED_GLASS_PANE
            BlockType.BLACK_TERRACOTTA -> Material.BLACK_TERRACOTTA
            BlockType.BLACK_WALL_BANNER -> Material.BLACK_WALL_BANNER
            BlockType.BLACK_WOOL -> Material.BLACK_WOOL
            BlockType.BLUE_BANNER -> Material.BLUE_BANNER
            BlockType.BLUE_BED -> Material.BLUE_BED
            BlockType.BLUE_CARPET -> Material.BLUE_CARPET
            BlockType.BLUE_CONCRETE -> Material.BLUE_CONCRETE
            BlockType.BLUE_CONCRETE_POWDER -> Material.BLUE_CONCRETE_POWDER
            BlockType.BLUE_GLAZED_TERRACOTTA -> Material.BLUE_GLAZED_TERRACOTTA
            BlockType.BLUE_ICE -> Material.BLUE_ICE
            BlockType.BLUE_ORCHID -> Material.BLUE_ORCHID
            BlockType.BLUE_SHULKER_BOX -> Material.BLUE_SHULKER_BOX
            BlockType.BLUE_STAINED_GLASS -> Material.BLUE_STAINED_GLASS
            BlockType.BLUE_STAINED_GLASS_PANE -> Material.BLUE_STAINED_GLASS_PANE
            BlockType.BLUE_TERRACOTTA -> Material.BLUE_TERRACOTTA
            BlockType.BLUE_WALL_BANNER -> Material.BLUE_WALL_BANNER
            BlockType.BLUE_WOOL -> Material.BLUE_WOOL
            BlockType.BONE_BLOCK -> Material.BONE_BLOCK
            BlockType.BOOKSHELF -> Material.BOOKSHELF
            BlockType.BRAIN_CORAL -> Material.BRAIN_CORAL
            BlockType.BRAIN_CORAL_BLOCK -> Material.BRAIN_CORAL_BLOCK
            BlockType.BRAIN_CORAL_FAN -> Material.BRAIN_CORAL_FAN
            BlockType.BRAIN_CORAL_WALL_FAN -> Material.BRAIN_CORAL_WALL_FAN
            BlockType.BREWING_STAND -> Material.BREWING_STAND
            BlockType.BRICKS -> Material.BRICKS
            BlockType.BRICK_SLAB -> Material.BRICK_SLAB
            BlockType.BRICK_STAIRS -> Material.BRICK_STAIRS
            BlockType.BROWN_BANNER -> Material.BROWN_BANNER
            BlockType.BROWN_BED -> Material.BROWN_BED
            BlockType.BROWN_CARPET -> Material.BROWN_CARPET
            BlockType.BROWN_CONCRETE -> Material.BROWN_CONCRETE
            BlockType.BROWN_CONCRETE_POWDER -> Material.BROWN_CONCRETE_POWDER
            BlockType.BROWN_GLAZED_TERRACOTTA -> Material.BROWN_GLAZED_TERRACOTTA
            BlockType.BROWN_MUSHROOM -> Material.BROWN_MUSHROOM
            BlockType.BROWN_MUSHROOM_BLOCK -> Material.BROWN_MUSHROOM_BLOCK
            BlockType.BROWN_SHULKER_BOX -> Material.BROWN_SHULKER_BOX
            BlockType.BROWN_STAINED_GLASS -> Material.BROWN_STAINED_GLASS
            BlockType.BROWN_STAINED_GLASS_PANE -> Material.BROWN_STAINED_GLASS_PANE
            BlockType.BROWN_TERRACOTTA -> Material.BROWN_TERRACOTTA
            BlockType.BROWN_WALL_BANNER -> Material.BROWN_WALL_BANNER
            BlockType.BROWN_WOOL -> Material.BROWN_WOOL
            BlockType.BUBBLE_COLUMN -> Material.BUBBLE_COLUMN
            BlockType.BUBBLE_CORAL -> Material.BUBBLE_CORAL
            BlockType.BUBBLE_CORAL_BLOCK -> Material.BUBBLE_CORAL_BLOCK
            BlockType.BUBBLE_CORAL_FAN -> Material.BUBBLE_CORAL_FAN
            BlockType.BUBBLE_CORAL_WALL_FAN -> Material.BUBBLE_CORAL_WALL_FAN
            BlockType.CACTUS -> Material.CACTUS
            BlockType.CAKE -> Material.CAKE
            BlockType.CARROTS -> Material.CARROTS
            BlockType.CARVED_PUMPKIN -> Material.CARVED_PUMPKIN
            BlockType.CAULDRON -> Material.CAULDRON
            BlockType.CAVE_AIR -> Material.CAVE_AIR
            BlockType.CHAIN_COMMAND_BLOCK -> Material.CHAIN_COMMAND_BLOCK
            BlockType.CHEST -> Material.CHEST
            BlockType.CHIPPED_ANVIL -> Material.CHIPPED_ANVIL
            BlockType.CHISELED_QUARTZ_BLOCK -> Material.CHISELED_QUARTZ_BLOCK
            BlockType.CHISELED_RED_SANDSTONE -> Material.CHISELED_RED_SANDSTONE
            BlockType.CHISELED_SANDSTONE -> Material.CHISELED_SANDSTONE
            BlockType.CHISELED_STONE_BRICKS -> Material.CHISELED_STONE_BRICKS
            BlockType.CHORUS_FLOWER -> Material.CHORUS_FLOWER
            BlockType.CHORUS_PLANT -> Material.CHORUS_PLANT
            BlockType.CLAY -> Material.CLAY
            BlockType.COAL_BLOCK -> Material.COAL_BLOCK
            BlockType.COAL_ORE -> Material.COAL_ORE
            BlockType.COARSE_DIRT -> Material.COARSE_DIRT
            BlockType.COBBLESTONE -> Material.COBBLESTONE
            BlockType.COBBLESTONE_SLAB -> Material.COBBLESTONE_SLAB
            BlockType.COBBLESTONE_STAIRS -> Material.COBBLESTONE_STAIRS
            BlockType.COBBLESTONE_WALL -> Material.COBBLESTONE_WALL
            BlockType.COBWEB -> Material.COBWEB
            BlockType.COCOA -> Material.COCOA
            BlockType.COMMAND_BLOCK -> Material.COMMAND_BLOCK
            BlockType.COMPARATOR -> Material.COMPARATOR
            BlockType.CONDUIT -> Material.CONDUIT
            BlockType.CRACKED_STONE_BRICKS -> Material.CRACKED_STONE_BRICKS
            BlockType.CRAFTING_TABLE -> Material.CRAFTING_TABLE
            BlockType.CREEPER_HEAD -> Material.CREEPER_HEAD
            BlockType.CREEPER_WALL_HEAD -> Material.CREEPER_WALL_HEAD
            BlockType.CUT_RED_SANDSTONE -> Material.CUT_RED_SANDSTONE
            BlockType.CUT_SANDSTONE -> Material.CUT_SANDSTONE
            BlockType.CYAN_BANNER -> Material.CYAN_BANNER
            BlockType.CYAN_BED -> Material.CYAN_BED
            BlockType.CYAN_CARPET -> Material.CYAN_CARPET
            BlockType.CYAN_CONCRETE -> Material.CYAN_CONCRETE
            BlockType.CYAN_CONCRETE_POWDER -> Material.CYAN_CONCRETE_POWDER
            BlockType.CYAN_GLAZED_TERRACOTTA -> Material.CYAN_GLAZED_TERRACOTTA
            BlockType.CYAN_SHULKER_BOX -> Material.CYAN_SHULKER_BOX
            BlockType.CYAN_STAINED_GLASS -> Material.CYAN_STAINED_GLASS
            BlockType.CYAN_STAINED_GLASS_PANE -> Material.CYAN_STAINED_GLASS_PANE
            BlockType.CYAN_TERRACOTTA -> Material.CYAN_TERRACOTTA
            BlockType.CYAN_WALL_BANNER -> Material.CYAN_WALL_BANNER
            BlockType.CYAN_WOOL -> Material.CYAN_WOOL
            BlockType.DAMAGED_ANVIL -> Material.DAMAGED_ANVIL
            BlockType.DANDELION -> Material.DANDELION
            BlockType.DARK_OAK_BUTTON -> Material.DARK_OAK_BUTTON
            BlockType.DARK_OAK_DOOR -> Material.DARK_OAK_DOOR
            BlockType.DARK_OAK_FENCE -> Material.DARK_OAK_FENCE
            BlockType.DARK_OAK_FENCE_GATE -> Material.DARK_OAK_FENCE_GATE
            BlockType.DARK_OAK_LEAVES -> Material.DARK_OAK_LEAVES
            BlockType.DARK_OAK_LOG -> Material.DARK_OAK_LOG
            BlockType.DARK_OAK_PLANKS -> Material.DARK_OAK_PLANKS
            BlockType.DARK_OAK_PRESSURE_PLATE -> Material.DARK_OAK_PRESSURE_PLATE
            BlockType.DARK_OAK_SAPLING -> Material.DARK_OAK_SAPLING
            BlockType.DARK_OAK_SLAB -> Material.DARK_OAK_SLAB
            BlockType.DARK_OAK_STAIRS -> Material.DARK_OAK_STAIRS
            BlockType.DARK_OAK_TRAPDOOR -> Material.DARK_OAK_TRAPDOOR
            BlockType.DARK_OAK_WOOD -> Material.DARK_OAK_WOOD
            BlockType.DARK_PRISMARINE -> Material.DARK_PRISMARINE
            BlockType.DARK_PRISMARINE_SLAB -> Material.DARK_PRISMARINE_SLAB
            BlockType.DARK_PRISMARINE_STAIRS -> Material.DARK_PRISMARINE_STAIRS
            BlockType.DAYLIGHT_DETECTOR -> Material.DAYLIGHT_DETECTOR
            BlockType.DEAD_BRAIN_CORAL_BLOCK -> Material.DEAD_BRAIN_CORAL_BLOCK
            BlockType.DEAD_BRAIN_CORAL_FAN -> Material.DEAD_BRAIN_CORAL_FAN
            BlockType.DEAD_BRAIN_CORAL_WALL_FAN -> Material.DEAD_BRAIN_CORAL_WALL_FAN
            BlockType.DEAD_BUBBLE_CORAL_BLOCK -> Material.DEAD_BUBBLE_CORAL_BLOCK
            BlockType.DEAD_BUBBLE_CORAL_FAN -> Material.DEAD_BUBBLE_CORAL_FAN
            BlockType.DEAD_BUBBLE_CORAL_WALL_FAN -> Material.DEAD_BUBBLE_CORAL_WALL_FAN
            BlockType.DEAD_BUSH -> Material.DEAD_BUSH
            BlockType.DEAD_FIRE_CORAL_BLOCK -> Material.DEAD_FIRE_CORAL_BLOCK
            BlockType.DEAD_FIRE_CORAL_FAN -> Material.DEAD_FIRE_CORAL_FAN
            BlockType.DEAD_FIRE_CORAL_WALL_FAN -> Material.DEAD_FIRE_CORAL_WALL_FAN
            BlockType.DEAD_HORN_CORAL_BLOCK -> Material.DEAD_HORN_CORAL_BLOCK
            BlockType.DEAD_HORN_CORAL_FAN -> Material.DEAD_HORN_CORAL_FAN
            BlockType.DEAD_HORN_CORAL_WALL_FAN -> Material.DEAD_HORN_CORAL_WALL_FAN
            BlockType.DEAD_TUBE_CORAL_BLOCK -> Material.DEAD_TUBE_CORAL_BLOCK
            BlockType.DEAD_TUBE_CORAL_FAN -> Material.DEAD_TUBE_CORAL_FAN
            BlockType.DEAD_TUBE_CORAL_WALL_FAN -> Material.DEAD_TUBE_CORAL_WALL_FAN
            BlockType.DETECTOR_RAIL -> Material.DETECTOR_RAIL
            BlockType.DIAMOND_BLOCK -> Material.DIAMOND_BLOCK
            BlockType.DIAMOND_ORE -> Material.DIAMOND_ORE
            BlockType.DIORITE -> Material.DIORITE
            BlockType.DIRT -> Material.DIRT
            BlockType.DISPENSER -> Material.DISPENSER
            BlockType.DRAGON_EGG -> Material.DRAGON_EGG
            BlockType.DRAGON_HEAD -> Material.DRAGON_HEAD
            BlockType.DRAGON_WALL_HEAD -> Material.DRAGON_WALL_HEAD
            BlockType.DRIED_KELP_BLOCK -> Material.DRIED_KELP_BLOCK
            BlockType.DROPPER -> Material.DROPPER
            BlockType.EMERALD_BLOCK -> Material.EMERALD_BLOCK
            BlockType.EMERALD_ORE -> Material.EMERALD_ORE
            BlockType.ENCHANTING_TABLE -> Material.ENCHANTING_TABLE
            BlockType.ENDER_CHEST -> Material.ENDER_CHEST
            BlockType.END_GATEWAY -> Material.END_GATEWAY
            BlockType.END_PORTAL -> Material.END_PORTAL
            BlockType.END_PORTAL_FRAME -> Material.END_PORTAL_FRAME
            BlockType.END_ROD -> Material.END_ROD
            BlockType.END_STONE -> Material.END_STONE
            BlockType.END_STONE_BRICKS -> Material.END_STONE_BRICKS
            BlockType.FARMLAND -> Material.FARMLAND
            BlockType.FERN -> Material.FERN
            BlockType.FIRE -> Material.FIRE
            BlockType.FIRE_CORAL -> Material.FIRE_CORAL
            BlockType.FIRE_CORAL_BLOCK -> Material.FIRE_CORAL_BLOCK
            BlockType.FIRE_CORAL_FAN -> Material.FIRE_CORAL_FAN
            BlockType.FIRE_CORAL_WALL_FAN -> Material.FIRE_CORAL_WALL_FAN
            BlockType.FLOWER_POT -> Material.FLOWER_POT
            BlockType.FROSTED_ICE -> Material.FROSTED_ICE
            BlockType.FURNACE -> Material.FURNACE
            BlockType.GLASS -> Material.GLASS
            BlockType.GLASS_PANE -> Material.GLASS_PANE
            BlockType.GLOWSTONE -> Material.GLOWSTONE
            BlockType.GOLD_BLOCK -> Material.GOLD_BLOCK
            BlockType.GOLD_ORE -> Material.GOLD_ORE
            BlockType.GRANITE -> Material.GRANITE
            BlockType.GRASS -> Material.GRASS
            BlockType.GRASS_BLOCK -> Material.GRASS_BLOCK
            BlockType.GRASS_PATH -> Material.GRASS_PATH
            BlockType.GRAVEL -> Material.GRAVEL
            BlockType.GRAY_BANNER -> Material.GRAY_BANNER
            BlockType.GRAY_BED -> Material.GRAY_BED
            BlockType.GRAY_CARPET -> Material.GRAY_CARPET
            BlockType.GRAY_CONCRETE -> Material.GRAY_CONCRETE
            BlockType.GRAY_CONCRETE_POWDER -> Material.GRAY_CONCRETE_POWDER
            BlockType.GRAY_GLAZED_TERRACOTTA -> Material.GRAY_GLAZED_TERRACOTTA
            BlockType.GRAY_SHULKER_BOX -> Material.GRAY_SHULKER_BOX
            BlockType.GRAY_STAINED_GLASS -> Material.GRAY_STAINED_GLASS
            BlockType.GRAY_STAINED_GLASS_PANE -> Material.GRAY_STAINED_GLASS_PANE
            BlockType.GRAY_TERRACOTTA -> Material.GRAY_TERRACOTTA
            BlockType.GRAY_WALL_BANNER -> Material.GRAY_WALL_BANNER
            BlockType.GRAY_WOOL -> Material.GRAY_WOOL
            BlockType.GREEN_BANNER -> Material.GREEN_BANNER
            BlockType.GREEN_BED -> Material.GREEN_BED
            BlockType.GREEN_CARPET -> Material.GREEN_CARPET
            BlockType.GREEN_CONCRETE -> Material.GREEN_CONCRETE
            BlockType.GREEN_CONCRETE_POWDER -> Material.GREEN_CONCRETE_POWDER
            BlockType.GREEN_GLAZED_TERRACOTTA -> Material.GREEN_GLAZED_TERRACOTTA
            BlockType.GREEN_SHULKER_BOX -> Material.GREEN_SHULKER_BOX
            BlockType.GREEN_STAINED_GLASS -> Material.GREEN_STAINED_GLASS
            BlockType.GREEN_STAINED_GLASS_PANE -> Material.GREEN_STAINED_GLASS_PANE
            BlockType.GREEN_TERRACOTTA -> Material.GREEN_TERRACOTTA
            BlockType.GREEN_WALL_BANNER -> Material.GREEN_WALL_BANNER
            BlockType.GREEN_WOOL -> Material.GREEN_WOOL
            BlockType.HAY_BLOCK -> Material.HAY_BLOCK
            BlockType.HEAVY_WEIGHTED_PRESSURE_PLATE -> Material.HEAVY_WEIGHTED_PRESSURE_PLATE
            BlockType.HOPPER -> Material.HOPPER
            BlockType.HORN_CORAL -> Material.HORN_CORAL
            BlockType.HORN_CORAL_BLOCK -> Material.HORN_CORAL_BLOCK
            BlockType.HORN_CORAL_FAN -> Material.HORN_CORAL_FAN
            BlockType.HORN_CORAL_WALL_FAN -> Material.HORN_CORAL_WALL_FAN
            BlockType.ICE -> Material.ICE
            BlockType.INFESTED_CHISELED_STONE_BRICKS -> Material.INFESTED_CHISELED_STONE_BRICKS
            BlockType.INFESTED_COBBLESTONE -> Material.INFESTED_COBBLESTONE
            BlockType.INFESTED_CRACKED_STONE_BRICKS -> Material.INFESTED_CRACKED_STONE_BRICKS
            BlockType.INFESTED_MOSSY_STONE_BRICKS -> Material.INFESTED_MOSSY_STONE_BRICKS
            BlockType.INFESTED_STONE -> Material.INFESTED_STONE
            BlockType.INFESTED_STONE_BRICKS -> Material.INFESTED_STONE_BRICKS
            BlockType.IRON_BARS -> Material.IRON_BARS
            BlockType.IRON_BLOCK -> Material.IRON_BLOCK
            BlockType.IRON_DOOR -> Material.IRON_DOOR
            BlockType.IRON_ORE -> Material.IRON_ORE
            BlockType.IRON_TRAPDOOR -> Material.IRON_TRAPDOOR
            BlockType.JACK_O_LANTERN -> Material.JACK_O_LANTERN
            BlockType.JUKEBOX -> Material.JUKEBOX
            BlockType.JUNGLE_BUTTON -> Material.JUNGLE_BUTTON
            BlockType.JUNGLE_DOOR -> Material.JUNGLE_DOOR
            BlockType.JUNGLE_FENCE -> Material.JUNGLE_FENCE
            BlockType.JUNGLE_FENCE_GATE -> Material.JUNGLE_FENCE_GATE
            BlockType.JUNGLE_LEAVES -> Material.JUNGLE_LEAVES
            BlockType.JUNGLE_LOG -> Material.JUNGLE_LOG
            BlockType.JUNGLE_PLANKS -> Material.JUNGLE_PLANKS
            BlockType.JUNGLE_PRESSURE_PLATE -> Material.JUNGLE_PRESSURE_PLATE
            BlockType.JUNGLE_SAPLING -> Material.JUNGLE_SAPLING
            BlockType.JUNGLE_SLAB -> Material.JUNGLE_SLAB
            BlockType.JUNGLE_STAIRS -> Material.JUNGLE_STAIRS
            BlockType.JUNGLE_TRAPDOOR -> Material.JUNGLE_TRAPDOOR
            BlockType.JUNGLE_WOOD -> Material.JUNGLE_WOOD
            BlockType.KELP -> Material.KELP
            BlockType.KELP_PLANT -> Material.KELP_PLANT
            BlockType.LADDER -> Material.LADDER
            BlockType.LAPIS_BLOCK -> Material.LAPIS_BLOCK
            BlockType.LAPIS_ORE -> Material.LAPIS_ORE
            BlockType.LARGE_FERN -> Material.LARGE_FERN
            BlockType.LAVA -> Material.LAVA
            BlockType.LEVER -> Material.LEVER
            BlockType.LIGHT_BLUE_BANNER -> Material.LIGHT_BLUE_BANNER
            BlockType.LIGHT_BLUE_BED -> Material.LIGHT_BLUE_BED
            BlockType.LIGHT_BLUE_CARPET -> Material.LIGHT_BLUE_CARPET
            BlockType.LIGHT_BLUE_CONCRETE -> Material.LIGHT_BLUE_CONCRETE
            BlockType.LIGHT_BLUE_CONCRETE_POWDER -> Material.LIGHT_BLUE_CONCRETE_POWDER
            BlockType.LIGHT_BLUE_GLAZED_TERRACOTTA -> Material.LIGHT_BLUE_GLAZED_TERRACOTTA
            BlockType.LIGHT_BLUE_SHULKER_BOX -> Material.LIGHT_BLUE_SHULKER_BOX
            BlockType.LIGHT_BLUE_STAINED_GLASS -> Material.LIGHT_BLUE_STAINED_GLASS
            BlockType.LIGHT_BLUE_STAINED_GLASS_PANE -> Material.LIGHT_BLUE_STAINED_GLASS_PANE
            BlockType.LIGHT_BLUE_TERRACOTTA -> Material.LIGHT_BLUE_TERRACOTTA
            BlockType.LIGHT_BLUE_WALL_BANNER -> Material.LIGHT_BLUE_WALL_BANNER
            BlockType.LIGHT_BLUE_WOOL -> Material.LIGHT_BLUE_WOOL
            BlockType.LIGHT_GRAY_BANNER -> Material.LIGHT_GRAY_BANNER
            BlockType.LIGHT_GRAY_BED -> Material.LIGHT_GRAY_BED
            BlockType.LIGHT_GRAY_CARPET -> Material.LIGHT_GRAY_CARPET
            BlockType.LIGHT_GRAY_CONCRETE -> Material.LIGHT_GRAY_CONCRETE
            BlockType.LIGHT_GRAY_CONCRETE_POWDER -> Material.LIGHT_GRAY_CONCRETE_POWDER
            BlockType.LIGHT_GRAY_GLAZED_TERRACOTTA -> Material.LIGHT_GRAY_GLAZED_TERRACOTTA
            BlockType.LIGHT_GRAY_SHULKER_BOX -> Material.LIGHT_GRAY_SHULKER_BOX
            BlockType.LIGHT_GRAY_STAINED_GLASS -> Material.LIGHT_GRAY_STAINED_GLASS
            BlockType.LIGHT_GRAY_STAINED_GLASS_PANE -> Material.LIGHT_GRAY_STAINED_GLASS_PANE
            BlockType.LIGHT_GRAY_TERRACOTTA -> Material.LIGHT_GRAY_TERRACOTTA
            BlockType.LIGHT_GRAY_WALL_BANNER -> Material.LIGHT_GRAY_WALL_BANNER
            BlockType.LIGHT_GRAY_WOOL -> Material.LIGHT_GRAY_WOOL
            BlockType.LIGHT_WEIGHTED_PRESSURE_PLATE -> Material.LIGHT_WEIGHTED_PRESSURE_PLATE
            BlockType.LILAC -> Material.LILAC
            BlockType.LILY_PAD -> Material.LILY_PAD
            BlockType.LIME_BANNER -> Material.LIME_BANNER
            BlockType.LIME_BED -> Material.LIME_BED
            BlockType.LIME_CARPET -> Material.LIME_CARPET
            BlockType.LIME_CONCRETE -> Material.LIME_CONCRETE
            BlockType.LIME_CONCRETE_POWDER -> Material.LIME_CONCRETE_POWDER
            BlockType.LIME_GLAZED_TERRACOTTA -> Material.LIME_GLAZED_TERRACOTTA
            BlockType.LIME_SHULKER_BOX -> Material.LIME_SHULKER_BOX
            BlockType.LIME_STAINED_GLASS -> Material.LIME_STAINED_GLASS
            BlockType.LIME_STAINED_GLASS_PANE -> Material.LIME_STAINED_GLASS_PANE
            BlockType.LIME_TERRACOTTA -> Material.LIME_TERRACOTTA
            BlockType.LIME_WALL_BANNER -> Material.LIME_WALL_BANNER
            BlockType.LIME_WOOL -> Material.LIME_WOOL
            BlockType.MAGENTA_BANNER -> Material.MAGENTA_BANNER
            BlockType.MAGENTA_BED -> Material.MAGENTA_BED
            BlockType.MAGENTA_CARPET -> Material.MAGENTA_CARPET
            BlockType.MAGENTA_CONCRETE -> Material.MAGENTA_CONCRETE
            BlockType.MAGENTA_CONCRETE_POWDER -> Material.MAGENTA_CONCRETE_POWDER
            BlockType.MAGENTA_GLAZED_TERRACOTTA -> Material.MAGENTA_GLAZED_TERRACOTTA
            BlockType.MAGENTA_SHULKER_BOX -> Material.MAGENTA_SHULKER_BOX
            BlockType.MAGENTA_STAINED_GLASS -> Material.MAGENTA_STAINED_GLASS
            BlockType.MAGENTA_STAINED_GLASS_PANE -> Material.MAGENTA_STAINED_GLASS_PANE
            BlockType.MAGENTA_TERRACOTTA -> Material.MAGENTA_TERRACOTTA
            BlockType.MAGENTA_WALL_BANNER -> Material.MAGENTA_WALL_BANNER
            BlockType.MAGENTA_WOOL -> Material.MAGENTA_WOOL
            BlockType.MAGMA_BLOCK -> Material.MAGMA_BLOCK
            BlockType.MELON -> Material.MELON
            BlockType.MELON_STEM -> Material.MELON_STEM
            BlockType.MOSSY_COBBLESTONE -> Material.MOSSY_COBBLESTONE
            BlockType.MOSSY_COBBLESTONE_WALL -> Material.MOSSY_COBBLESTONE_WALL
            BlockType.MOSSY_STONE_BRICKS -> Material.MOSSY_STONE_BRICKS
            BlockType.MOVING_PISTON -> Material.MOVING_PISTON
            BlockType.MUSHROOM_STEM -> Material.MUSHROOM_STEM
            BlockType.MYCELIUM -> Material.MYCELIUM
            BlockType.NETHERRACK -> Material.NETHERRACK
            BlockType.NETHER_BRICKS -> Material.NETHER_BRICKS
            BlockType.NETHER_BRICK_FENCE -> Material.NETHER_BRICK_FENCE
            BlockType.NETHER_BRICK_SLAB -> Material.NETHER_BRICK_SLAB
            BlockType.NETHER_BRICK_STAIRS -> Material.NETHER_BRICK_STAIRS
            BlockType.NETHER_PORTAL -> Material.NETHER_PORTAL
            BlockType.NETHER_QUARTZ_ORE -> Material.NETHER_QUARTZ_ORE
            BlockType.NETHER_WART -> Material.NETHER_WART
            BlockType.NETHER_WART_BLOCK -> Material.NETHER_WART_BLOCK
            BlockType.NOTE_BLOCK -> Material.NOTE_BLOCK
            BlockType.OAK_BUTTON -> Material.OAK_BUTTON
            BlockType.OAK_DOOR -> Material.OAK_DOOR
            BlockType.OAK_FENCE -> Material.OAK_FENCE
            BlockType.OAK_FENCE_GATE -> Material.OAK_FENCE_GATE
            BlockType.OAK_LEAVES -> Material.OAK_LEAVES
            BlockType.OAK_LOG -> Material.OAK_LOG
            BlockType.OAK_PLANKS -> Material.OAK_PLANKS
            BlockType.OAK_PRESSURE_PLATE -> Material.OAK_PRESSURE_PLATE
            BlockType.OAK_SAPLING -> Material.OAK_SAPLING
            BlockType.OAK_SLAB -> Material.OAK_SLAB
            BlockType.OAK_STAIRS -> Material.OAK_STAIRS
            BlockType.OAK_TRAPDOOR -> Material.OAK_TRAPDOOR
            BlockType.OAK_WOOD -> Material.OAK_WOOD
            BlockType.OBSERVER -> Material.OBSERVER
            BlockType.OBSIDIAN -> Material.OBSIDIAN
            BlockType.ORANGE_BANNER -> Material.ORANGE_BANNER
            BlockType.ORANGE_BED -> Material.ORANGE_BED
            BlockType.ORANGE_CARPET -> Material.ORANGE_CARPET
            BlockType.ORANGE_CONCRETE -> Material.ORANGE_CONCRETE
            BlockType.ORANGE_CONCRETE_POWDER -> Material.ORANGE_CONCRETE_POWDER
            BlockType.ORANGE_GLAZED_TERRACOTTA -> Material.ORANGE_GLAZED_TERRACOTTA
            BlockType.ORANGE_SHULKER_BOX -> Material.ORANGE_SHULKER_BOX
            BlockType.ORANGE_STAINED_GLASS -> Material.ORANGE_STAINED_GLASS
            BlockType.ORANGE_STAINED_GLASS_PANE -> Material.ORANGE_STAINED_GLASS_PANE
            BlockType.ORANGE_TERRACOTTA -> Material.ORANGE_TERRACOTTA
            BlockType.ORANGE_TULIP -> Material.ORANGE_TULIP
            BlockType.ORANGE_WALL_BANNER -> Material.ORANGE_WALL_BANNER
            BlockType.ORANGE_WOOL -> Material.ORANGE_WOOL
            BlockType.OXEYE_DAISY -> Material.OXEYE_DAISY
            BlockType.PACKED_ICE -> Material.PACKED_ICE
            BlockType.PEONY -> Material.PEONY
            BlockType.PETRIFIED_OAK_SLAB -> Material.PETRIFIED_OAK_SLAB
            BlockType.PINK_BANNER -> Material.PINK_BANNER
            BlockType.PINK_BED -> Material.PINK_BED
            BlockType.PINK_CARPET -> Material.PINK_CARPET
            BlockType.PINK_CONCRETE -> Material.PINK_CONCRETE
            BlockType.PINK_CONCRETE_POWDER -> Material.PINK_CONCRETE_POWDER
            BlockType.PINK_GLAZED_TERRACOTTA -> Material.PINK_GLAZED_TERRACOTTA
            BlockType.PINK_SHULKER_BOX -> Material.PINK_SHULKER_BOX
            BlockType.PINK_STAINED_GLASS -> Material.PINK_STAINED_GLASS
            BlockType.PINK_STAINED_GLASS_PANE -> Material.PINK_STAINED_GLASS_PANE
            BlockType.PINK_TERRACOTTA -> Material.PINK_TERRACOTTA
            BlockType.PINK_TULIP -> Material.PINK_TULIP
            BlockType.PINK_WALL_BANNER -> Material.PINK_WALL_BANNER
            BlockType.PINK_WOOL -> Material.PINK_WOOL
            BlockType.PISTON -> Material.PISTON
            BlockType.PISTON_HEAD -> Material.PISTON_HEAD
            BlockType.PLAYER_HEAD -> Material.PLAYER_HEAD
            BlockType.PLAYER_WALL_HEAD -> Material.PLAYER_WALL_HEAD
            BlockType.PODZOL -> Material.PODZOL
            BlockType.POLISHED_ANDESITE -> Material.POLISHED_ANDESITE
            BlockType.POLISHED_DIORITE -> Material.POLISHED_DIORITE
            BlockType.POLISHED_GRANITE -> Material.POLISHED_GRANITE
            BlockType.POPPY -> Material.POPPY
            BlockType.POTATOES -> Material.POTATOES
            BlockType.POTTED_ACACIA_SAPLING -> Material.POTTED_ACACIA_SAPLING
            BlockType.POTTED_ALLIUM -> Material.POTTED_ALLIUM
            BlockType.POTTED_AZURE_BLUET -> Material.POTTED_AZURE_BLUET
            BlockType.POTTED_BIRCH_SAPLING -> Material.POTTED_BIRCH_SAPLING
            BlockType.POTTED_BLUE_ORCHID -> Material.POTTED_BLUE_ORCHID
            BlockType.POTTED_BROWN_MUSHROOM -> Material.POTTED_BROWN_MUSHROOM
            BlockType.POTTED_CACTUS -> Material.POTTED_CACTUS
            BlockType.POTTED_DANDELION -> Material.POTTED_DANDELION
            BlockType.POTTED_DARK_OAK_SAPLING -> Material.POTTED_DARK_OAK_SAPLING
            BlockType.POTTED_DEAD_BUSH -> Material.POTTED_DEAD_BUSH
            BlockType.POTTED_FERN -> Material.POTTED_FERN
            BlockType.POTTED_JUNGLE_SAPLING -> Material.POTTED_JUNGLE_SAPLING
            BlockType.POTTED_OAK_SAPLING -> Material.POTTED_OAK_SAPLING
            BlockType.POTTED_ORANGE_TULIP -> Material.POTTED_ORANGE_TULIP
            BlockType.POTTED_OXEYE_DAISY -> Material.POTTED_OXEYE_DAISY
            BlockType.POTTED_PINK_TULIP -> Material.POTTED_PINK_TULIP
            BlockType.POTTED_POPPY -> Material.POTTED_POPPY
            BlockType.POTTED_RED_MUSHROOM -> Material.POTTED_RED_MUSHROOM
            BlockType.POTTED_RED_TULIP -> Material.POTTED_RED_TULIP
            BlockType.POTTED_SPRUCE_SAPLING -> Material.POTTED_SPRUCE_SAPLING
            BlockType.POTTED_WHITE_TULIP -> Material.POTTED_WHITE_TULIP
            BlockType.POWERED_RAIL -> Material.POWERED_RAIL
            BlockType.PRISMARINE -> Material.PRISMARINE
            BlockType.PRISMARINE_BRICKS -> Material.PRISMARINE_BRICKS
            BlockType.PRISMARINE_BRICK_SLAB -> Material.PRISMARINE_BRICK_SLAB
            BlockType.PRISMARINE_BRICK_STAIRS -> Material.PRISMARINE_BRICK_STAIRS
            BlockType.PRISMARINE_SLAB -> Material.PRISMARINE_SLAB
            BlockType.PRISMARINE_STAIRS -> Material.PRISMARINE_STAIRS
            BlockType.PUMPKIN -> Material.PUMPKIN
            BlockType.PUMPKIN_STEM -> Material.PUMPKIN_STEM
            BlockType.PURPLE_BANNER -> Material.PURPLE_BANNER
            BlockType.PURPLE_BED -> Material.PURPLE_BED
            BlockType.PURPLE_CARPET -> Material.PURPLE_CARPET
            BlockType.PURPLE_CONCRETE -> Material.PURPLE_CONCRETE
            BlockType.PURPLE_CONCRETE_POWDER -> Material.PURPLE_CONCRETE_POWDER
            BlockType.PURPLE_GLAZED_TERRACOTTA -> Material.PURPLE_GLAZED_TERRACOTTA
            BlockType.PURPLE_SHULKER_BOX -> Material.PURPLE_SHULKER_BOX
            BlockType.PURPLE_STAINED_GLASS -> Material.PURPLE_STAINED_GLASS
            BlockType.PURPLE_STAINED_GLASS_PANE -> Material.PURPLE_STAINED_GLASS_PANE
            BlockType.PURPLE_TERRACOTTA -> Material.PURPLE_TERRACOTTA
            BlockType.PURPLE_WALL_BANNER -> Material.PURPLE_WALL_BANNER
            BlockType.PURPLE_WOOL -> Material.PURPLE_WOOL
            BlockType.PURPUR_BLOCK -> Material.PURPUR_BLOCK
            BlockType.PURPUR_PILLAR -> Material.PURPUR_PILLAR
            BlockType.PURPUR_SLAB -> Material.PURPUR_SLAB
            BlockType.PURPUR_STAIRS -> Material.PURPUR_STAIRS
            BlockType.QUARTZ_BLOCK -> Material.QUARTZ_BLOCK
            BlockType.QUARTZ_PILLAR -> Material.QUARTZ_PILLAR
            BlockType.QUARTZ_SLAB -> Material.QUARTZ_SLAB
            BlockType.QUARTZ_STAIRS -> Material.QUARTZ_STAIRS
            BlockType.RAIL -> Material.RAIL
            BlockType.REDSTONE_BLOCK -> Material.REDSTONE_BLOCK
            BlockType.REDSTONE_LAMP -> Material.REDSTONE_LAMP
            BlockType.REDSTONE_ORE -> Material.REDSTONE_ORE
            BlockType.REDSTONE_TORCH -> Material.REDSTONE_TORCH
            BlockType.REDSTONE_WALL_TORCH -> Material.REDSTONE_WALL_TORCH
            BlockType.REDSTONE_WIRE -> Material.REDSTONE_WIRE
            BlockType.RED_BANNER -> Material.RED_BANNER
            BlockType.RED_BED -> Material.RED_BED
            BlockType.RED_CARPET -> Material.RED_CARPET
            BlockType.RED_CONCRETE -> Material.RED_CONCRETE
            BlockType.RED_CONCRETE_POWDER -> Material.RED_CONCRETE_POWDER
            BlockType.RED_GLAZED_TERRACOTTA -> Material.RED_GLAZED_TERRACOTTA
            BlockType.RED_MUSHROOM -> Material.RED_MUSHROOM
            BlockType.RED_MUSHROOM_BLOCK -> Material.RED_MUSHROOM_BLOCK
            BlockType.RED_NETHER_BRICKS -> Material.RED_NETHER_BRICKS
            BlockType.RED_SAND -> Material.RED_SAND
            BlockType.RED_SANDSTONE -> Material.RED_SANDSTONE
            BlockType.RED_SANDSTONE_SLAB -> Material.RED_SANDSTONE_SLAB
            BlockType.RED_SANDSTONE_STAIRS -> Material.RED_SANDSTONE_STAIRS
            BlockType.RED_SHULKER_BOX -> Material.RED_SHULKER_BOX
            BlockType.RED_STAINED_GLASS -> Material.RED_STAINED_GLASS
            BlockType.RED_STAINED_GLASS_PANE -> Material.RED_STAINED_GLASS_PANE
            BlockType.RED_TERRACOTTA -> Material.RED_TERRACOTTA
            BlockType.RED_TULIP -> Material.RED_TULIP
            BlockType.RED_WALL_BANNER -> Material.RED_WALL_BANNER
            BlockType.RED_WOOL -> Material.RED_WOOL
            BlockType.REPEATER -> Material.REPEATER
            BlockType.REPEATING_COMMAND_BLOCK -> Material.REPEATING_COMMAND_BLOCK
            BlockType.ROSE_BUSH -> Material.ROSE_BUSH
            BlockType.SAND -> Material.SAND
            BlockType.SANDSTONE -> Material.SANDSTONE
            BlockType.SANDSTONE_SLAB -> Material.SANDSTONE_SLAB
            BlockType.SANDSTONE_STAIRS -> Material.SANDSTONE_STAIRS
            BlockType.SEAGRASS -> Material.SEAGRASS
            BlockType.SEA_LANTERN -> Material.SEA_LANTERN
            BlockType.SEA_PICKLE -> Material.SEA_PICKLE
            BlockType.SHULKER_BOX -> Material.SHULKER_BOX
            BlockType.SIGN -> Material.SIGN
            BlockType.SKELETON_SKULL -> Material.SKELETON_SKULL
            BlockType.SKELETON_WALL_SKULL -> Material.SKELETON_WALL_SKULL
            BlockType.SLIME_BLOCK -> Material.SLIME_BLOCK
            BlockType.SMOOTH_QUARTZ -> Material.SMOOTH_QUARTZ
            BlockType.SMOOTH_RED_SANDSTONE -> Material.SMOOTH_RED_SANDSTONE
            BlockType.SMOOTH_SANDSTONE -> Material.SMOOTH_SANDSTONE
            BlockType.SMOOTH_STONE -> Material.SMOOTH_STONE
            BlockType.SNOW -> Material.SNOW
            BlockType.SNOW_BLOCK -> Material.SNOW_BLOCK
            BlockType.SOUL_SAND -> Material.SOUL_SAND
            BlockType.SPAWNER -> Material.SPAWNER
            BlockType.SPONGE -> Material.SPONGE
            BlockType.SPRUCE_BUTTON -> Material.SPRUCE_BUTTON
            BlockType.SPRUCE_DOOR -> Material.SPRUCE_DOOR
            BlockType.SPRUCE_FENCE -> Material.SPRUCE_FENCE
            BlockType.SPRUCE_FENCE_GATE -> Material.SPRUCE_FENCE_GATE
            BlockType.SPRUCE_LEAVES -> Material.SPRUCE_LEAVES
            BlockType.SPRUCE_LOG -> Material.SPRUCE_LOG
            BlockType.SPRUCE_PLANKS -> Material.SPRUCE_PLANKS
            BlockType.SPRUCE_PRESSURE_PLATE -> Material.SPRUCE_PRESSURE_PLATE
            BlockType.SPRUCE_SAPLING -> Material.SPRUCE_SAPLING
            BlockType.SPRUCE_SLAB -> Material.SPRUCE_SLAB
            BlockType.SPRUCE_STAIRS -> Material.SPRUCE_STAIRS
            BlockType.SPRUCE_TRAPDOOR -> Material.SPRUCE_TRAPDOOR
            BlockType.SPRUCE_WOOD -> Material.SPRUCE_WOOD
            BlockType.STICKY_PISTON -> Material.STICKY_PISTON
            BlockType.STONE -> Material.STONE
            BlockType.STONE_BRICKS -> Material.STONE_BRICKS
            BlockType.STONE_BRICK_SLAB -> Material.STONE_BRICK_SLAB
            BlockType.STONE_BRICK_STAIRS -> Material.STONE_BRICK_STAIRS
            BlockType.STONE_BUTTON -> Material.STONE_BUTTON
            BlockType.STONE_PRESSURE_PLATE -> Material.STONE_PRESSURE_PLATE
            BlockType.STONE_SLAB -> Material.STONE_SLAB
            BlockType.STRIPPED_ACACIA_LOG -> Material.STRIPPED_ACACIA_LOG
            BlockType.STRIPPED_ACACIA_WOOD -> Material.STRIPPED_ACACIA_WOOD
            BlockType.STRIPPED_BIRCH_LOG -> Material.STRIPPED_BIRCH_LOG
            BlockType.STRIPPED_BIRCH_WOOD -> Material.STRIPPED_BIRCH_WOOD
            BlockType.STRIPPED_DARK_OAK_LOG -> Material.STRIPPED_DARK_OAK_LOG
            BlockType.STRIPPED_DARK_OAK_WOOD -> Material.STRIPPED_DARK_OAK_WOOD
            BlockType.STRIPPED_JUNGLE_LOG -> Material.STRIPPED_JUNGLE_LOG
            BlockType.STRIPPED_JUNGLE_WOOD -> Material.STRIPPED_JUNGLE_WOOD
            BlockType.STRIPPED_OAK_LOG -> Material.STRIPPED_OAK_LOG
            BlockType.STRIPPED_OAK_WOOD -> Material.STRIPPED_OAK_WOOD
            BlockType.STRIPPED_SPRUCE_LOG -> Material.STRIPPED_SPRUCE_LOG
            BlockType.STRIPPED_SPRUCE_WOOD -> Material.STRIPPED_SPRUCE_WOOD
            BlockType.STRUCTURE_BLOCK -> Material.STRUCTURE_BLOCK
            BlockType.STRUCTURE_VOID -> Material.STRUCTURE_VOID
            BlockType.SUGAR_CANE -> Material.SUGAR_CANE
            BlockType.SUNFLOWER -> Material.SUNFLOWER
            BlockType.TALL_GRASS -> Material.TALL_GRASS
            BlockType.TALL_SEAGRASS -> Material.TALL_SEAGRASS
            BlockType.TERRACOTTA -> Material.TERRACOTTA
            BlockType.TNT -> Material.TNT
            BlockType.TORCH -> Material.TORCH
            BlockType.TRAPPED_CHEST -> Material.TRAPPED_CHEST
            BlockType.TRIPWIRE -> Material.TRIPWIRE
            BlockType.TRIPWIRE_HOOK -> Material.TRIPWIRE_HOOK
            BlockType.TUBE_CORAL -> Material.TUBE_CORAL
            BlockType.TUBE_CORAL_BLOCK -> Material.TUBE_CORAL_BLOCK
            BlockType.TUBE_CORAL_FAN -> Material.TUBE_CORAL_FAN
            BlockType.TUBE_CORAL_WALL_FAN -> Material.TUBE_CORAL_WALL_FAN
            BlockType.TURTLE_EGG -> Material.TURTLE_EGG
            BlockType.VINE -> Material.VINE
            BlockType.VOID_AIR -> Material.VOID_AIR
            BlockType.WALL_SIGN -> Material.WALL_SIGN
            BlockType.WALL_TORCH -> Material.WALL_TORCH
            BlockType.WATER -> Material.WATER
            BlockType.WET_SPONGE -> Material.WET_SPONGE
            BlockType.WHEAT -> Material.WHEAT
            BlockType.WHITE_BANNER -> Material.WHITE_BANNER
            BlockType.WHITE_BED -> Material.WHITE_BED
            BlockType.WHITE_CARPET -> Material.WHITE_CARPET
            BlockType.WHITE_CONCRETE -> Material.WHITE_CONCRETE
            BlockType.WHITE_CONCRETE_POWDER -> Material.WHITE_CONCRETE_POWDER
            BlockType.WHITE_GLAZED_TERRACOTTA -> Material.WHITE_GLAZED_TERRACOTTA
            BlockType.WHITE_SHULKER_BOX -> Material.WHITE_SHULKER_BOX
            BlockType.WHITE_STAINED_GLASS -> Material.WHITE_STAINED_GLASS
            BlockType.WHITE_STAINED_GLASS_PANE -> Material.WHITE_STAINED_GLASS_PANE
            BlockType.WHITE_TERRACOTTA -> Material.WHITE_TERRACOTTA
            BlockType.WHITE_TULIP -> Material.WHITE_TULIP
            BlockType.WHITE_WALL_BANNER -> Material.WHITE_WALL_BANNER
            BlockType.WHITE_WOOL -> Material.WHITE_WOOL
            BlockType.WITHER_SKELETON_SKULL -> Material.WITHER_SKELETON_SKULL
            BlockType.WITHER_SKELETON_WALL_SKULL -> Material.WITHER_SKELETON_WALL_SKULL
            BlockType.YELLOW_BANNER -> Material.YELLOW_BANNER
            BlockType.YELLOW_BED -> Material.YELLOW_BED
            BlockType.YELLOW_CARPET -> Material.YELLOW_CARPET
            BlockType.YELLOW_CONCRETE -> Material.YELLOW_CONCRETE
            BlockType.YELLOW_CONCRETE_POWDER -> Material.YELLOW_CONCRETE_POWDER
            BlockType.YELLOW_GLAZED_TERRACOTTA -> Material.YELLOW_GLAZED_TERRACOTTA
            BlockType.YELLOW_SHULKER_BOX -> Material.YELLOW_SHULKER_BOX
            BlockType.YELLOW_STAINED_GLASS -> Material.YELLOW_STAINED_GLASS
            BlockType.YELLOW_STAINED_GLASS_PANE -> Material.YELLOW_STAINED_GLASS_PANE
            BlockType.YELLOW_TERRACOTTA -> Material.YELLOW_TERRACOTTA
            BlockType.YELLOW_WALL_BANNER -> Material.YELLOW_WALL_BANNER
            BlockType.YELLOW_WOOL -> Material.YELLOW_WOOL
            BlockType.ZOMBIE_HEAD -> Material.ZOMBIE_HEAD
            BlockType.ZOMBIE_WALL_HEAD -> Material.ZOMBIE_WALL_HEAD
            //</editor-fold>
        }
    }
}