package net.craftlin.bukkit.impl.value

import net.craftlin.api.util.value.EnumValue
import net.craftlin.api.value.ItemType
import org.bukkit.Material

object BukkitItemType: EnumValue<ItemType, Material>(ItemType::class) {
    override fun convert(api: ItemType) = when(api) {
        ItemType.ACACIA_BOAT -> Material.ACACIA_BOAT
        ItemType.ACACIA_BUTTON -> Material.ACACIA_BUTTON
        ItemType.ACACIA_DOOR -> Material.ACACIA_DOOR
        ItemType.ACACIA_FENCE -> Material.ACACIA_FENCE
        ItemType.ACACIA_FENCE_GATE -> Material.ACACIA_FENCE_GATE
        ItemType.ACACIA_LEAVES -> Material.ACACIA_LEAVES
        ItemType.ACACIA_LOG -> Material.ACACIA_LOG
        ItemType.ACACIA_PLANKS -> Material.ACACIA_PLANKS
        ItemType.ACACIA_PRESSURE_PLATE -> Material.ACACIA_PRESSURE_PLATE
        ItemType.ACACIA_SAPLING -> Material.ACACIA_SAPLING
        ItemType.ACACIA_SLAB -> Material.ACACIA_SLAB
        ItemType.ACACIA_STAIRS -> Material.ACACIA_STAIRS
        ItemType.ACACIA_TRAPDOOR -> Material.ACACIA_TRAPDOOR
        ItemType.ACACIA_WOOD -> Material.ACACIA_WOOD
        ItemType.ACTIVATOR_RAIL -> Material.ACTIVATOR_RAIL
        ItemType.AIR -> Material.AIR
        ItemType.ALLIUM -> Material.ALLIUM
        ItemType.ANDESITE -> Material.ANDESITE
        ItemType.ANVIL -> Material.ANVIL
        ItemType.APPLE -> Material.APPLE
        ItemType.ARMOR_STAND -> Material.ARMOR_STAND
        ItemType.ARROW -> Material.ARROW
        ItemType.ATTACHED_MELON_STEM -> Material.ATTACHED_MELON_STEM
        ItemType.ATTACHED_PUMPKIN_STEM -> Material.ATTACHED_PUMPKIN_STEM
        ItemType.AZURE_BLUET -> Material.AZURE_BLUET
        ItemType.BAKED_POTATO -> Material.BAKED_POTATO
        ItemType.BARRIER -> Material.BARRIER
        ItemType.BAT_SPAWN_EGG -> Material.BAT_SPAWN_EGG
        ItemType.BEACON -> Material.BEACON
        ItemType.BEDROCK -> Material.BEDROCK
        ItemType.BEEF -> Material.BEEF
        ItemType.BEETROOT -> Material.BEETROOT
        ItemType.BEETROOTS -> Material.BEETROOTS
        ItemType.BEETROOT_SEEDS -> Material.BEETROOT_SEEDS
        ItemType.BEETROOT_SOUP -> Material.BEETROOT_SOUP
        ItemType.BIRCH_BOAT -> Material.BIRCH_BOAT
        ItemType.BIRCH_BUTTON -> Material.BIRCH_BUTTON
        ItemType.BIRCH_DOOR -> Material.BIRCH_DOOR
        ItemType.BIRCH_FENCE -> Material.BIRCH_FENCE
        ItemType.BIRCH_FENCE_GATE -> Material.BIRCH_FENCE_GATE
        ItemType.BIRCH_LEAVES -> Material.BIRCH_LEAVES
        ItemType.BIRCH_LOG -> Material.BIRCH_LOG
        ItemType.BIRCH_PLANKS -> Material.BIRCH_PLANKS
        ItemType.BIRCH_PRESSURE_PLATE -> Material.BIRCH_PRESSURE_PLATE
        ItemType.BIRCH_SAPLING -> Material.BIRCH_SAPLING
        ItemType.BIRCH_SLAB -> Material.BIRCH_SLAB
        ItemType.BIRCH_STAIRS -> Material.BIRCH_STAIRS
        ItemType.BIRCH_TRAPDOOR -> Material.BIRCH_TRAPDOOR
        ItemType.BIRCH_WOOD -> Material.BIRCH_WOOD
        ItemType.BLACK_BANNER -> Material.BLACK_BANNER
        ItemType.BLACK_BED -> Material.BLACK_BED
        ItemType.BLACK_CARPET -> Material.BLACK_CARPET
        ItemType.BLACK_CONCRETE -> Material.BLACK_CONCRETE
        ItemType.BLACK_CONCRETE_POWDER -> Material.BLACK_CONCRETE_POWDER
        ItemType.BLACK_GLAZED_TERRACOTTA -> Material.BLACK_GLAZED_TERRACOTTA
        ItemType.BLACK_SHULKER_BOX -> Material.BLACK_SHULKER_BOX
        ItemType.BLACK_STAINED_GLASS -> Material.BLACK_STAINED_GLASS
        ItemType.BLACK_STAINED_GLASS_PANE -> Material.BLACK_STAINED_GLASS_PANE
        ItemType.BLACK_TERRACOTTA -> Material.BLACK_TERRACOTTA
        ItemType.BLACK_WALL_BANNER -> Material.BLACK_WALL_BANNER
        ItemType.BLACK_WOOL -> Material.BLACK_WOOL
        ItemType.BLAZE_POWDER -> Material.BLAZE_POWDER
        ItemType.BLAZE_ROD -> Material.BLAZE_ROD
        ItemType.BLAZE_SPAWN_EGG -> Material.BLAZE_SPAWN_EGG
        ItemType.BLUE_BANNER -> Material.BLUE_BANNER
        ItemType.BLUE_BED -> Material.BLUE_BED
        ItemType.BLUE_CARPET -> Material.BLUE_CARPET
        ItemType.BLUE_CONCRETE -> Material.BLUE_CONCRETE
        ItemType.BLUE_CONCRETE_POWDER -> Material.BLUE_CONCRETE_POWDER
        ItemType.BLUE_GLAZED_TERRACOTTA -> Material.BLUE_GLAZED_TERRACOTTA
        ItemType.BLUE_ICE -> Material.BLUE_ICE
        ItemType.BLUE_ORCHID -> Material.BLUE_ORCHID
        ItemType.BLUE_SHULKER_BOX -> Material.BLUE_SHULKER_BOX
        ItemType.BLUE_STAINED_GLASS -> Material.BLUE_STAINED_GLASS
        ItemType.BLUE_STAINED_GLASS_PANE -> Material.BLUE_STAINED_GLASS_PANE
        ItemType.BLUE_TERRACOTTA -> Material.BLUE_TERRACOTTA
        ItemType.BLUE_WALL_BANNER -> Material.BLUE_WALL_BANNER
        ItemType.BLUE_WOOL -> Material.BLUE_WOOL
        ItemType.BONE -> Material.BONE
        ItemType.BONE_BLOCK -> Material.BONE_BLOCK
        ItemType.BONE_MEAL -> Material.BONE_MEAL
        ItemType.BOOK -> Material.BOOK
        ItemType.BOOKSHELF -> Material.BOOKSHELF
        ItemType.BOW -> Material.BOW
        ItemType.BOWL -> Material.BOWL
        ItemType.BRAIN_CORAL -> Material.BRAIN_CORAL
        ItemType.BRAIN_CORAL_BLOCK -> Material.BRAIN_CORAL_BLOCK
        ItemType.BRAIN_CORAL_FAN -> Material.BRAIN_CORAL_FAN
        ItemType.BRAIN_CORAL_WALL_FAN -> Material.BRAIN_CORAL_WALL_FAN
        ItemType.BREAD -> Material.BREAD
        ItemType.BREWING_STAND -> Material.BREWING_STAND
        ItemType.BRICK -> Material.BRICK
        ItemType.BRICKS -> Material.BRICKS
        ItemType.BRICK_SLAB -> Material.BRICK_SLAB
        ItemType.BRICK_STAIRS -> Material.BRICK_STAIRS
        ItemType.BROWN_BANNER -> Material.BROWN_BANNER
        ItemType.BROWN_BED -> Material.BROWN_BED
        ItemType.BROWN_CARPET -> Material.BROWN_CARPET
        ItemType.BROWN_CONCRETE -> Material.BROWN_CONCRETE
        ItemType.BROWN_CONCRETE_POWDER -> Material.BROWN_CONCRETE_POWDER
        ItemType.BROWN_GLAZED_TERRACOTTA -> Material.BROWN_GLAZED_TERRACOTTA
        ItemType.BROWN_MUSHROOM -> Material.BROWN_MUSHROOM
        ItemType.BROWN_MUSHROOM_BLOCK -> Material.BROWN_MUSHROOM_BLOCK
        ItemType.BROWN_SHULKER_BOX -> Material.BROWN_SHULKER_BOX
        ItemType.BROWN_STAINED_GLASS -> Material.BROWN_STAINED_GLASS
        ItemType.BROWN_STAINED_GLASS_PANE -> Material.BROWN_STAINED_GLASS_PANE
        ItemType.BROWN_TERRACOTTA -> Material.BROWN_TERRACOTTA
        ItemType.BROWN_WALL_BANNER -> Material.BROWN_WALL_BANNER
        ItemType.BROWN_WOOL -> Material.BROWN_WOOL
        ItemType.BUBBLE_COLUMN -> Material.BUBBLE_COLUMN
        ItemType.BUBBLE_CORAL -> Material.BUBBLE_CORAL
        ItemType.BUBBLE_CORAL_BLOCK -> Material.BUBBLE_CORAL_BLOCK
        ItemType.BUBBLE_CORAL_FAN -> Material.BUBBLE_CORAL_FAN
        ItemType.BUBBLE_CORAL_WALL_FAN -> Material.BUBBLE_CORAL_WALL_FAN
        ItemType.BUCKET -> Material.BUCKET
        ItemType.CACTUS -> Material.CACTUS
        ItemType.CACTUS_GREEN -> Material.CACTUS_GREEN
        ItemType.CAKE -> Material.CAKE
        ItemType.CARROT -> Material.CARROT
        ItemType.CARROTS -> Material.CARROTS
        ItemType.CARROT_ON_A_STICK -> Material.CARROT_ON_A_STICK
        ItemType.CARVED_PUMPKIN -> Material.CARVED_PUMPKIN
        ItemType.CAULDRON -> Material.CAULDRON
        ItemType.CAVE_AIR -> Material.CAVE_AIR
        ItemType.CAVE_SPIDER_SPAWN_EGG -> Material.CAVE_SPIDER_SPAWN_EGG
        ItemType.CHAINMAIL_BOOTS -> Material.CHAINMAIL_BOOTS
        ItemType.CHAINMAIL_CHESTPLATE -> Material.CHAINMAIL_CHESTPLATE
        ItemType.CHAINMAIL_HELMET -> Material.CHAINMAIL_HELMET
        ItemType.CHAINMAIL_LEGGINGS -> Material.CHAINMAIL_LEGGINGS
        ItemType.CHAIN_COMMAND_BLOCK -> Material.CHAIN_COMMAND_BLOCK
        ItemType.CHARCOAL -> Material.CHARCOAL
        ItemType.CHEST -> Material.CHEST
        ItemType.CHEST_MINECART -> Material.CHEST_MINECART
        ItemType.CHICKEN -> Material.CHICKEN
        ItemType.CHICKEN_SPAWN_EGG -> Material.CHICKEN_SPAWN_EGG
        ItemType.CHIPPED_ANVIL -> Material.CHIPPED_ANVIL
        ItemType.CHISELED_QUARTZ_BLOCK -> Material.CHISELED_QUARTZ_BLOCK
        ItemType.CHISELED_RED_SANDSTONE -> Material.CHISELED_RED_SANDSTONE
        ItemType.CHISELED_SANDSTONE -> Material.CHISELED_SANDSTONE
        ItemType.CHISELED_STONE_BRICKS -> Material.CHISELED_STONE_BRICKS
        ItemType.CHORUS_FLOWER -> Material.CHORUS_FLOWER
        ItemType.CHORUS_FRUIT -> Material.CHORUS_FRUIT
        ItemType.CHORUS_PLANT -> Material.CHORUS_PLANT
        ItemType.CLAY -> Material.CLAY
        ItemType.CLAY_BALL -> Material.CLAY_BALL
        ItemType.CLOCK -> Material.CLOCK
        ItemType.COAL -> Material.COAL
        ItemType.COAL_BLOCK -> Material.COAL_BLOCK
        ItemType.COAL_ORE -> Material.COAL_ORE
        ItemType.COARSE_DIRT -> Material.COARSE_DIRT
        ItemType.COBBLESTONE -> Material.COBBLESTONE
        ItemType.COBBLESTONE_SLAB -> Material.COBBLESTONE_SLAB
        ItemType.COBBLESTONE_STAIRS -> Material.COBBLESTONE_STAIRS
        ItemType.COBBLESTONE_WALL -> Material.COBBLESTONE_WALL
        ItemType.COBWEB -> Material.COBWEB
        ItemType.COCOA -> Material.COCOA
        ItemType.COCOA_BEANS -> Material.COCOA_BEANS
        ItemType.COD -> Material.COD
        ItemType.COD_BUCKET -> Material.COD_BUCKET
        ItemType.COD_SPAWN_EGG -> Material.COD_SPAWN_EGG
        ItemType.COMMAND_BLOCK -> Material.COMMAND_BLOCK
        ItemType.COMMAND_BLOCK_MINECART -> Material.COMMAND_BLOCK_MINECART
        ItemType.COMPARATOR -> Material.COMPARATOR
        ItemType.COMPASS -> Material.COMPASS
        ItemType.CONDUIT -> Material.CONDUIT
        ItemType.COOKED_BEEF -> Material.COOKED_BEEF
        ItemType.COOKED_CHICKEN -> Material.COOKED_CHICKEN
        ItemType.COOKED_COD -> Material.COOKED_COD
        ItemType.COOKED_MUTTON -> Material.COOKED_MUTTON
        ItemType.COOKED_PORKCHOP -> Material.COOKED_PORKCHOP
        ItemType.COOKED_RABBIT -> Material.COOKED_RABBIT
        ItemType.COOKED_SALMON -> Material.COOKED_SALMON
        ItemType.COOKIE -> Material.COOKIE
        ItemType.COW_SPAWN_EGG -> Material.COW_SPAWN_EGG
        ItemType.CRACKED_STONE_BRICKS -> Material.CRACKED_STONE_BRICKS
        ItemType.CRAFTING_TABLE -> Material.CRAFTING_TABLE
        ItemType.CREEPER_HEAD -> Material.CREEPER_HEAD
        ItemType.CREEPER_SPAWN_EGG -> Material.CREEPER_SPAWN_EGG
        ItemType.CREEPER_WALL_HEAD -> Material.CREEPER_WALL_HEAD
        ItemType.CUT_RED_SANDSTONE -> Material.CUT_RED_SANDSTONE
        ItemType.CUT_SANDSTONE -> Material.CUT_SANDSTONE
        ItemType.CYAN_BANNER -> Material.CYAN_BANNER
        ItemType.CYAN_BED -> Material.CYAN_BED
        ItemType.CYAN_CARPET -> Material.CYAN_CARPET
        ItemType.CYAN_CONCRETE -> Material.CYAN_CONCRETE
        ItemType.CYAN_CONCRETE_POWDER -> Material.CYAN_CONCRETE_POWDER
        ItemType.CYAN_DYE -> Material.CYAN_DYE
        ItemType.CYAN_GLAZED_TERRACOTTA -> Material.CYAN_GLAZED_TERRACOTTA
        ItemType.CYAN_SHULKER_BOX -> Material.CYAN_SHULKER_BOX
        ItemType.CYAN_STAINED_GLASS -> Material.CYAN_STAINED_GLASS
        ItemType.CYAN_STAINED_GLASS_PANE -> Material.CYAN_STAINED_GLASS_PANE
        ItemType.CYAN_TERRACOTTA -> Material.CYAN_TERRACOTTA
        ItemType.CYAN_WALL_BANNER -> Material.CYAN_WALL_BANNER
        ItemType.CYAN_WOOL -> Material.CYAN_WOOL
        ItemType.DAMAGED_ANVIL -> Material.DAMAGED_ANVIL
        ItemType.DANDELION -> Material.DANDELION
        ItemType.DANDELION_YELLOW -> Material.DANDELION_YELLOW
        ItemType.DARK_OAK_BOAT -> Material.DARK_OAK_BOAT
        ItemType.DARK_OAK_BUTTON -> Material.DARK_OAK_BUTTON
        ItemType.DARK_OAK_DOOR -> Material.DARK_OAK_DOOR
        ItemType.DARK_OAK_FENCE -> Material.DARK_OAK_FENCE
        ItemType.DARK_OAK_FENCE_GATE -> Material.DARK_OAK_FENCE_GATE
        ItemType.DARK_OAK_LEAVES -> Material.DARK_OAK_LEAVES
        ItemType.DARK_OAK_LOG -> Material.DARK_OAK_LOG
        ItemType.DARK_OAK_PLANKS -> Material.DARK_OAK_PLANKS
        ItemType.DARK_OAK_PRESSURE_PLATE -> Material.DARK_OAK_PRESSURE_PLATE
        ItemType.DARK_OAK_SAPLING -> Material.DARK_OAK_SAPLING
        ItemType.DARK_OAK_SLAB -> Material.DARK_OAK_SLAB
        ItemType.DARK_OAK_STAIRS -> Material.DARK_OAK_STAIRS
        ItemType.DARK_OAK_TRAPDOOR -> Material.DARK_OAK_TRAPDOOR
        ItemType.DARK_OAK_WOOD -> Material.DARK_OAK_WOOD
        ItemType.DARK_PRISMARINE -> Material.DARK_PRISMARINE
        ItemType.DARK_PRISMARINE_SLAB -> Material.DARK_PRISMARINE_SLAB
        ItemType.DARK_PRISMARINE_STAIRS -> Material.DARK_PRISMARINE_STAIRS
        ItemType.DAYLIGHT_DETECTOR -> Material.DAYLIGHT_DETECTOR
        ItemType.DEAD_BRAIN_CORAL_BLOCK -> Material.DEAD_BRAIN_CORAL_BLOCK
        ItemType.DEAD_BRAIN_CORAL_FAN -> Material.DEAD_BRAIN_CORAL_FAN
        ItemType.DEAD_BRAIN_CORAL_WALL_FAN -> Material.DEAD_BRAIN_CORAL_WALL_FAN
        ItemType.DEAD_BUBBLE_CORAL_BLOCK -> Material.DEAD_BUBBLE_CORAL_BLOCK
        ItemType.DEAD_BUBBLE_CORAL_FAN -> Material.DEAD_BUBBLE_CORAL_FAN
        ItemType.DEAD_BUBBLE_CORAL_WALL_FAN -> Material.DEAD_BUBBLE_CORAL_WALL_FAN
        ItemType.DEAD_BUSH -> Material.DEAD_BUSH
        ItemType.DEAD_FIRE_CORAL_BLOCK -> Material.DEAD_FIRE_CORAL_BLOCK
        ItemType.DEAD_FIRE_CORAL_FAN -> Material.DEAD_FIRE_CORAL_FAN
        ItemType.DEAD_FIRE_CORAL_WALL_FAN -> Material.DEAD_FIRE_CORAL_WALL_FAN
        ItemType.DEAD_HORN_CORAL_BLOCK -> Material.DEAD_HORN_CORAL_BLOCK
        ItemType.DEAD_HORN_CORAL_FAN -> Material.DEAD_HORN_CORAL_FAN
        ItemType.DEAD_HORN_CORAL_WALL_FAN -> Material.DEAD_HORN_CORAL_WALL_FAN
        ItemType.DEAD_TUBE_CORAL_BLOCK -> Material.DEAD_TUBE_CORAL_BLOCK
        ItemType.DEAD_TUBE_CORAL_FAN -> Material.DEAD_TUBE_CORAL_FAN
        ItemType.DEAD_TUBE_CORAL_WALL_FAN -> Material.DEAD_TUBE_CORAL_WALL_FAN
        ItemType.DEBUG_STICK -> Material.DEBUG_STICK
        ItemType.DETECTOR_RAIL -> Material.DETECTOR_RAIL
        ItemType.DIAMOND -> Material.DIAMOND
        ItemType.DIAMOND_AXE -> Material.DIAMOND_AXE
        ItemType.DIAMOND_BLOCK -> Material.DIAMOND_BLOCK
        ItemType.DIAMOND_BOOTS -> Material.DIAMOND_BOOTS
        ItemType.DIAMOND_CHESTPLATE -> Material.DIAMOND_CHESTPLATE
        ItemType.DIAMOND_HELMET -> Material.DIAMOND_HELMET
        ItemType.DIAMOND_HOE -> Material.DIAMOND_HOE
        ItemType.DIAMOND_HORSE_ARMOR -> Material.DIAMOND_HORSE_ARMOR
        ItemType.DIAMOND_LEGGINGS -> Material.DIAMOND_LEGGINGS
        ItemType.DIAMOND_ORE -> Material.DIAMOND_ORE
        ItemType.DIAMOND_PICKAXE -> Material.DIAMOND_PICKAXE
        ItemType.DIAMOND_SHOVEL -> Material.DIAMOND_SHOVEL
        ItemType.DIAMOND_SWORD -> Material.DIAMOND_SWORD
        ItemType.DIORITE -> Material.DIORITE
        ItemType.DIRT -> Material.DIRT
        ItemType.DISPENSER -> Material.DISPENSER
        ItemType.DOLPHIN_SPAWN_EGG -> Material.DOLPHIN_SPAWN_EGG
        ItemType.DONKEY_SPAWN_EGG -> Material.DONKEY_SPAWN_EGG
        ItemType.DRAGON_BREATH -> Material.DRAGON_BREATH
        ItemType.DRAGON_EGG -> Material.DRAGON_EGG
        ItemType.DRAGON_HEAD -> Material.DRAGON_HEAD
        ItemType.DRAGON_WALL_HEAD -> Material.DRAGON_WALL_HEAD
        ItemType.DRIED_KELP -> Material.DRIED_KELP
        ItemType.DRIED_KELP_BLOCK -> Material.DRIED_KELP_BLOCK
        ItemType.DROPPER -> Material.DROPPER
        ItemType.DROWNED_SPAWN_EGG -> Material.DROWNED_SPAWN_EGG
        ItemType.EGG -> Material.EGG
        ItemType.ELDER_GUARDIAN_SPAWN_EGG -> Material.ELDER_GUARDIAN_SPAWN_EGG
        ItemType.ELYTRA -> Material.ELYTRA
        ItemType.EMERALD -> Material.EMERALD
        ItemType.EMERALD_BLOCK -> Material.EMERALD_BLOCK
        ItemType.EMERALD_ORE -> Material.EMERALD_ORE
        ItemType.ENCHANTED_BOOK -> Material.ENCHANTED_BOOK
        ItemType.ENCHANTED_GOLDEN_APPLE -> Material.ENCHANTED_GOLDEN_APPLE
        ItemType.ENCHANTING_TABLE -> Material.ENCHANTING_TABLE
        ItemType.ENDERMAN_SPAWN_EGG -> Material.ENDERMAN_SPAWN_EGG
        ItemType.ENDERMITE_SPAWN_EGG -> Material.ENDERMITE_SPAWN_EGG
        ItemType.ENDER_CHEST -> Material.ENDER_CHEST
        ItemType.ENDER_EYE -> Material.ENDER_EYE
        ItemType.ENDER_PEARL -> Material.ENDER_PEARL
        ItemType.END_CRYSTAL -> Material.END_CRYSTAL
        ItemType.END_GATEWAY -> Material.END_GATEWAY
        ItemType.END_PORTAL -> Material.END_PORTAL
        ItemType.END_PORTAL_FRAME -> Material.END_PORTAL_FRAME
        ItemType.END_ROD -> Material.END_ROD
        ItemType.END_STONE -> Material.END_STONE
        ItemType.END_STONE_BRICKS -> Material.END_STONE_BRICKS
        ItemType.EVOKER_SPAWN_EGG -> Material.EVOKER_SPAWN_EGG
        ItemType.EXPERIENCE_BOTTLE -> Material.EXPERIENCE_BOTTLE
        ItemType.FARMLAND -> Material.FARMLAND
        ItemType.FEATHER -> Material.FEATHER
        ItemType.FERMENTED_SPIDER_EYE -> Material.FERMENTED_SPIDER_EYE
        ItemType.FERN -> Material.FERN
        ItemType.FILLED_MAP -> Material.FILLED_MAP
        ItemType.FIRE -> Material.FIRE
        ItemType.FIREWORK_ROCKET -> Material.FIREWORK_ROCKET
        ItemType.FIREWORK_STAR -> Material.FIREWORK_STAR
        ItemType.FIRE_CHARGE -> Material.FIRE_CHARGE
        ItemType.FIRE_CORAL -> Material.FIRE_CORAL
        ItemType.FIRE_CORAL_BLOCK -> Material.FIRE_CORAL_BLOCK
        ItemType.FIRE_CORAL_FAN -> Material.FIRE_CORAL_FAN
        ItemType.FIRE_CORAL_WALL_FAN -> Material.FIRE_CORAL_WALL_FAN
        ItemType.FISHING_ROD -> Material.FISHING_ROD
        ItemType.FLINT -> Material.FLINT
        ItemType.FLINT_AND_STEEL -> Material.FLINT_AND_STEEL
        ItemType.FLOWER_POT -> Material.FLOWER_POT
        ItemType.FROSTED_ICE -> Material.FROSTED_ICE
        ItemType.FURNACE -> Material.FURNACE
        ItemType.FURNACE_MINECART -> Material.FURNACE_MINECART
        ItemType.GHAST_SPAWN_EGG -> Material.GHAST_SPAWN_EGG
        ItemType.GHAST_TEAR -> Material.GHAST_TEAR
        ItemType.GLASS -> Material.GLASS
        ItemType.GLASS_BOTTLE -> Material.GLASS_BOTTLE
        ItemType.GLASS_PANE -> Material.GLASS_PANE
        ItemType.GLISTERING_MELON_SLICE -> Material.GLISTERING_MELON_SLICE
        ItemType.GLOWSTONE -> Material.GLOWSTONE
        ItemType.GLOWSTONE_DUST -> Material.GLOWSTONE_DUST
        ItemType.GOLDEN_APPLE -> Material.GOLDEN_APPLE
        ItemType.GOLDEN_AXE -> Material.GOLDEN_AXE
        ItemType.GOLDEN_BOOTS -> Material.GOLDEN_BOOTS
        ItemType.GOLDEN_CARROT -> Material.GOLDEN_CARROT
        ItemType.GOLDEN_CHESTPLATE -> Material.GOLDEN_CHESTPLATE
        ItemType.GOLDEN_HELMET -> Material.GOLDEN_HELMET
        ItemType.GOLDEN_HOE -> Material.GOLDEN_HOE
        ItemType.GOLDEN_HORSE_ARMOR -> Material.GOLDEN_HORSE_ARMOR
        ItemType.GOLDEN_LEGGINGS -> Material.GOLDEN_LEGGINGS
        ItemType.GOLDEN_PICKAXE -> Material.GOLDEN_PICKAXE
        ItemType.GOLDEN_SHOVEL -> Material.GOLDEN_SHOVEL
        ItemType.GOLDEN_SWORD -> Material.GOLDEN_SWORD
        ItemType.GOLD_BLOCK -> Material.GOLD_BLOCK
        ItemType.GOLD_INGOT -> Material.GOLD_INGOT
        ItemType.GOLD_NUGGET -> Material.GOLD_NUGGET
        ItemType.GOLD_ORE -> Material.GOLD_ORE
        ItemType.GRANITE -> Material.GRANITE
        ItemType.GRASS -> Material.GRASS
        ItemType.GRASS_BLOCK -> Material.GRASS_BLOCK
        ItemType.GRASS_PATH -> Material.GRASS_PATH
        ItemType.GRAVEL -> Material.GRAVEL
        ItemType.GRAY_BANNER -> Material.GRAY_BANNER
        ItemType.GRAY_BED -> Material.GRAY_BED
        ItemType.GRAY_CARPET -> Material.GRAY_CARPET
        ItemType.GRAY_CONCRETE -> Material.GRAY_CONCRETE
        ItemType.GRAY_CONCRETE_POWDER -> Material.GRAY_CONCRETE_POWDER
        ItemType.GRAY_DYE -> Material.GRAY_DYE
        ItemType.GRAY_GLAZED_TERRACOTTA -> Material.GRAY_GLAZED_TERRACOTTA
        ItemType.GRAY_SHULKER_BOX -> Material.GRAY_SHULKER_BOX
        ItemType.GRAY_STAINED_GLASS -> Material.GRAY_STAINED_GLASS
        ItemType.GRAY_STAINED_GLASS_PANE -> Material.GRAY_STAINED_GLASS_PANE
        ItemType.GRAY_TERRACOTTA -> Material.GRAY_TERRACOTTA
        ItemType.GRAY_WALL_BANNER -> Material.GRAY_WALL_BANNER
        ItemType.GRAY_WOOL -> Material.GRAY_WOOL
        ItemType.GREEN_BANNER -> Material.GREEN_BANNER
        ItemType.GREEN_BED -> Material.GREEN_BED
        ItemType.GREEN_CARPET -> Material.GREEN_CARPET
        ItemType.GREEN_CONCRETE -> Material.GREEN_CONCRETE
        ItemType.GREEN_CONCRETE_POWDER -> Material.GREEN_CONCRETE_POWDER
        ItemType.GREEN_GLAZED_TERRACOTTA -> Material.GREEN_GLAZED_TERRACOTTA
        ItemType.GREEN_SHULKER_BOX -> Material.GREEN_SHULKER_BOX
        ItemType.GREEN_STAINED_GLASS -> Material.GREEN_STAINED_GLASS
        ItemType.GREEN_STAINED_GLASS_PANE -> Material.GREEN_STAINED_GLASS_PANE
        ItemType.GREEN_TERRACOTTA -> Material.GREEN_TERRACOTTA
        ItemType.GREEN_WALL_BANNER -> Material.GREEN_WALL_BANNER
        ItemType.GREEN_WOOL -> Material.GREEN_WOOL
        ItemType.GUARDIAN_SPAWN_EGG -> Material.GUARDIAN_SPAWN_EGG
        ItemType.GUNPOWDER -> Material.GUNPOWDER
        ItemType.HAY_BLOCK -> Material.HAY_BLOCK
        ItemType.HEART_OF_THE_SEA -> Material.HEART_OF_THE_SEA
        ItemType.HEAVY_WEIGHTED_PRESSURE_PLATE -> Material.HEAVY_WEIGHTED_PRESSURE_PLATE
        ItemType.HOPPER -> Material.HOPPER
        ItemType.HOPPER_MINECART -> Material.HOPPER_MINECART
        ItemType.HORN_CORAL -> Material.HORN_CORAL
        ItemType.HORN_CORAL_BLOCK -> Material.HORN_CORAL_BLOCK
        ItemType.HORN_CORAL_FAN -> Material.HORN_CORAL_FAN
        ItemType.HORN_CORAL_WALL_FAN -> Material.HORN_CORAL_WALL_FAN
        ItemType.HORSE_SPAWN_EGG -> Material.HORSE_SPAWN_EGG
        ItemType.HUSK_SPAWN_EGG -> Material.HUSK_SPAWN_EGG
        ItemType.ICE -> Material.ICE
        ItemType.INFESTED_CHISELED_STONE_BRICKS -> Material.INFESTED_CHISELED_STONE_BRICKS
        ItemType.INFESTED_COBBLESTONE -> Material.INFESTED_COBBLESTONE
        ItemType.INFESTED_CRACKED_STONE_BRICKS -> Material.INFESTED_CRACKED_STONE_BRICKS
        ItemType.INFESTED_MOSSY_STONE_BRICKS -> Material.INFESTED_MOSSY_STONE_BRICKS
        ItemType.INFESTED_STONE -> Material.INFESTED_STONE
        ItemType.INFESTED_STONE_BRICKS -> Material.INFESTED_STONE_BRICKS
        ItemType.INK_SAC -> Material.INK_SAC
        ItemType.IRON_AXE -> Material.IRON_AXE
        ItemType.IRON_BARS -> Material.IRON_BARS
        ItemType.IRON_BLOCK -> Material.IRON_BLOCK
        ItemType.IRON_BOOTS -> Material.IRON_BOOTS
        ItemType.IRON_CHESTPLATE -> Material.IRON_CHESTPLATE
        ItemType.IRON_DOOR -> Material.IRON_DOOR
        ItemType.IRON_HELMET -> Material.IRON_HELMET
        ItemType.IRON_HOE -> Material.IRON_HOE
        ItemType.IRON_HORSE_ARMOR -> Material.IRON_HORSE_ARMOR
        ItemType.IRON_INGOT -> Material.IRON_INGOT
        ItemType.IRON_LEGGINGS -> Material.IRON_LEGGINGS
        ItemType.IRON_NUGGET -> Material.IRON_NUGGET
        ItemType.IRON_ORE -> Material.IRON_ORE
        ItemType.IRON_PICKAXE -> Material.IRON_PICKAXE
        ItemType.IRON_SHOVEL -> Material.IRON_SHOVEL
        ItemType.IRON_SWORD -> Material.IRON_SWORD
        ItemType.IRON_TRAPDOOR -> Material.IRON_TRAPDOOR
        ItemType.ITEM_FRAME -> Material.ITEM_FRAME
        ItemType.JACK_O_LANTERN -> Material.JACK_O_LANTERN
        ItemType.JUKEBOX -> Material.JUKEBOX
        ItemType.JUNGLE_BOAT -> Material.JUNGLE_BOAT
        ItemType.JUNGLE_BUTTON -> Material.JUNGLE_BUTTON
        ItemType.JUNGLE_DOOR -> Material.JUNGLE_DOOR
        ItemType.JUNGLE_FENCE -> Material.JUNGLE_FENCE
        ItemType.JUNGLE_FENCE_GATE -> Material.JUNGLE_FENCE_GATE
        ItemType.JUNGLE_LEAVES -> Material.JUNGLE_LEAVES
        ItemType.JUNGLE_LOG -> Material.JUNGLE_LOG
        ItemType.JUNGLE_PLANKS -> Material.JUNGLE_PLANKS
        ItemType.JUNGLE_PRESSURE_PLATE -> Material.JUNGLE_PRESSURE_PLATE
        ItemType.JUNGLE_SAPLING -> Material.JUNGLE_SAPLING
        ItemType.JUNGLE_SLAB -> Material.JUNGLE_SLAB
        ItemType.JUNGLE_STAIRS -> Material.JUNGLE_STAIRS
        ItemType.JUNGLE_TRAPDOOR -> Material.JUNGLE_TRAPDOOR
        ItemType.JUNGLE_WOOD -> Material.JUNGLE_WOOD
        ItemType.KELP -> Material.KELP
        ItemType.KELP_PLANT -> Material.KELP_PLANT
        ItemType.KNOWLEDGE_BOOK -> Material.KNOWLEDGE_BOOK
        ItemType.LADDER -> Material.LADDER
        ItemType.LAPIS_BLOCK -> Material.LAPIS_BLOCK
        ItemType.LAPIS_LAZULI -> Material.LAPIS_LAZULI
        ItemType.LAPIS_ORE -> Material.LAPIS_ORE
        ItemType.LARGE_FERN -> Material.LARGE_FERN
        ItemType.LAVA -> Material.LAVA
        ItemType.LAVA_BUCKET -> Material.LAVA_BUCKET
        ItemType.LEAD -> Material.LEAD
        ItemType.LEATHER -> Material.LEATHER
        ItemType.LEATHER_BOOTS -> Material.LEATHER_BOOTS
        ItemType.LEATHER_CHESTPLATE -> Material.LEATHER_CHESTPLATE
        ItemType.LEATHER_HELMET -> Material.LEATHER_HELMET
        ItemType.LEATHER_LEGGINGS -> Material.LEATHER_LEGGINGS
        ItemType.LEVER -> Material.LEVER
        ItemType.LIGHT_BLUE_BANNER -> Material.LIGHT_BLUE_BANNER
        ItemType.LIGHT_BLUE_BED -> Material.LIGHT_BLUE_BED
        ItemType.LIGHT_BLUE_CARPET -> Material.LIGHT_BLUE_CARPET
        ItemType.LIGHT_BLUE_CONCRETE -> Material.LIGHT_BLUE_CONCRETE
        ItemType.LIGHT_BLUE_CONCRETE_POWDER -> Material.LIGHT_BLUE_CONCRETE_POWDER
        ItemType.LIGHT_BLUE_DYE -> Material.LIGHT_BLUE_DYE
        ItemType.LIGHT_BLUE_GLAZED_TERRACOTTA -> Material.LIGHT_BLUE_GLAZED_TERRACOTTA
        ItemType.LIGHT_BLUE_SHULKER_BOX -> Material.LIGHT_BLUE_SHULKER_BOX
        ItemType.LIGHT_BLUE_STAINED_GLASS -> Material.LIGHT_BLUE_STAINED_GLASS
        ItemType.LIGHT_BLUE_STAINED_GLASS_PANE -> Material.LIGHT_BLUE_STAINED_GLASS_PANE
        ItemType.LIGHT_BLUE_TERRACOTTA -> Material.LIGHT_BLUE_TERRACOTTA
        ItemType.LIGHT_BLUE_WALL_BANNER -> Material.LIGHT_BLUE_WALL_BANNER
        ItemType.LIGHT_BLUE_WOOL -> Material.LIGHT_BLUE_WOOL
        ItemType.LIGHT_GRAY_BANNER -> Material.LIGHT_GRAY_BANNER
        ItemType.LIGHT_GRAY_BED -> Material.LIGHT_GRAY_BED
        ItemType.LIGHT_GRAY_CARPET -> Material.LIGHT_GRAY_CARPET
        ItemType.LIGHT_GRAY_CONCRETE -> Material.LIGHT_GRAY_CONCRETE
        ItemType.LIGHT_GRAY_CONCRETE_POWDER -> Material.LIGHT_GRAY_CONCRETE_POWDER
        ItemType.LIGHT_GRAY_DYE -> Material.LIGHT_GRAY_DYE
        ItemType.LIGHT_GRAY_GLAZED_TERRACOTTA -> Material.LIGHT_GRAY_GLAZED_TERRACOTTA
        ItemType.LIGHT_GRAY_SHULKER_BOX -> Material.LIGHT_GRAY_SHULKER_BOX
        ItemType.LIGHT_GRAY_STAINED_GLASS -> Material.LIGHT_GRAY_STAINED_GLASS
        ItemType.LIGHT_GRAY_STAINED_GLASS_PANE -> Material.LIGHT_GRAY_STAINED_GLASS_PANE
        ItemType.LIGHT_GRAY_TERRACOTTA -> Material.LIGHT_GRAY_TERRACOTTA
        ItemType.LIGHT_GRAY_WALL_BANNER -> Material.LIGHT_GRAY_WALL_BANNER
        ItemType.LIGHT_GRAY_WOOL -> Material.LIGHT_GRAY_WOOL
        ItemType.LIGHT_WEIGHTED_PRESSURE_PLATE -> Material.LIGHT_WEIGHTED_PRESSURE_PLATE
        ItemType.LILAC -> Material.LILAC
        ItemType.LILY_PAD -> Material.LILY_PAD
        ItemType.LIME_BANNER -> Material.LIME_BANNER
        ItemType.LIME_BED -> Material.LIME_BED
        ItemType.LIME_CARPET -> Material.LIME_CARPET
        ItemType.LIME_CONCRETE -> Material.LIME_CONCRETE
        ItemType.LIME_CONCRETE_POWDER -> Material.LIME_CONCRETE_POWDER
        ItemType.LIME_DYE -> Material.LIME_DYE
        ItemType.LIME_GLAZED_TERRACOTTA -> Material.LIME_GLAZED_TERRACOTTA
        ItemType.LIME_SHULKER_BOX -> Material.LIME_SHULKER_BOX
        ItemType.LIME_STAINED_GLASS -> Material.LIME_STAINED_GLASS
        ItemType.LIME_STAINED_GLASS_PANE -> Material.LIME_STAINED_GLASS_PANE
        ItemType.LIME_TERRACOTTA -> Material.LIME_TERRACOTTA
        ItemType.LIME_WALL_BANNER -> Material.LIME_WALL_BANNER
        ItemType.LIME_WOOL -> Material.LIME_WOOL
        ItemType.LINGERING_POTION -> Material.LINGERING_POTION
        ItemType.LLAMA_SPAWN_EGG -> Material.LLAMA_SPAWN_EGG
        ItemType.MAGENTA_BANNER -> Material.MAGENTA_BANNER
        ItemType.MAGENTA_BED -> Material.MAGENTA_BED
        ItemType.MAGENTA_CARPET -> Material.MAGENTA_CARPET
        ItemType.MAGENTA_CONCRETE -> Material.MAGENTA_CONCRETE
        ItemType.MAGENTA_CONCRETE_POWDER -> Material.MAGENTA_CONCRETE_POWDER
        ItemType.MAGENTA_DYE -> Material.MAGENTA_DYE
        ItemType.MAGENTA_GLAZED_TERRACOTTA -> Material.MAGENTA_GLAZED_TERRACOTTA
        ItemType.MAGENTA_SHULKER_BOX -> Material.MAGENTA_SHULKER_BOX
        ItemType.MAGENTA_STAINED_GLASS -> Material.MAGENTA_STAINED_GLASS
        ItemType.MAGENTA_STAINED_GLASS_PANE -> Material.MAGENTA_STAINED_GLASS_PANE
        ItemType.MAGENTA_TERRACOTTA -> Material.MAGENTA_TERRACOTTA
        ItemType.MAGENTA_WALL_BANNER -> Material.MAGENTA_WALL_BANNER
        ItemType.MAGENTA_WOOL -> Material.MAGENTA_WOOL
        ItemType.MAGMA_BLOCK -> Material.MAGMA_BLOCK
        ItemType.MAGMA_CREAM -> Material.MAGMA_CREAM
        ItemType.MAGMA_CUBE_SPAWN_EGG -> Material.MAGMA_CUBE_SPAWN_EGG
        ItemType.MAP -> Material.MAP
        ItemType.MELON -> Material.MELON
        ItemType.MELON_SEEDS -> Material.MELON_SEEDS
        ItemType.MELON_SLICE -> Material.MELON_SLICE
        ItemType.MELON_STEM -> Material.MELON_STEM
        ItemType.MILK_BUCKET -> Material.MILK_BUCKET
        ItemType.MINECART -> Material.MINECART
        ItemType.MOOSHROOM_SPAWN_EGG -> Material.MOOSHROOM_SPAWN_EGG
        ItemType.MOSSY_COBBLESTONE -> Material.MOSSY_COBBLESTONE
        ItemType.MOSSY_COBBLESTONE_WALL -> Material.MOSSY_COBBLESTONE_WALL
        ItemType.MOSSY_STONE_BRICKS -> Material.MOSSY_STONE_BRICKS
        ItemType.MOVING_PISTON -> Material.MOVING_PISTON
        ItemType.MULE_SPAWN_EGG -> Material.MULE_SPAWN_EGG
        ItemType.MUSHROOM_STEM -> Material.MUSHROOM_STEM
        ItemType.MUSHROOM_STEW -> Material.MUSHROOM_STEW
        ItemType.MUSIC_DISC_11 -> Material.MUSIC_DISC_11
        ItemType.MUSIC_DISC_13 -> Material.MUSIC_DISC_13
        ItemType.MUSIC_DISC_BLOCKS -> Material.MUSIC_DISC_BLOCKS
        ItemType.MUSIC_DISC_CAT -> Material.MUSIC_DISC_CAT
        ItemType.MUSIC_DISC_CHIRP -> Material.MUSIC_DISC_CHIRP
        ItemType.MUSIC_DISC_FAR -> Material.MUSIC_DISC_FAR
        ItemType.MUSIC_DISC_MALL -> Material.MUSIC_DISC_MALL
        ItemType.MUSIC_DISC_MELLOHI -> Material.MUSIC_DISC_MELLOHI
        ItemType.MUSIC_DISC_STAL -> Material.MUSIC_DISC_STAL
        ItemType.MUSIC_DISC_STRAD -> Material.MUSIC_DISC_STRAD
        ItemType.MUSIC_DISC_WAIT -> Material.MUSIC_DISC_WAIT
        ItemType.MUSIC_DISC_WARD -> Material.MUSIC_DISC_WARD
        ItemType.MUTTON -> Material.MUTTON
        ItemType.MYCELIUM -> Material.MYCELIUM
        ItemType.NAME_TAG -> Material.NAME_TAG
        ItemType.NAUTILUS_SHELL -> Material.NAUTILUS_SHELL
        ItemType.NETHERRACK -> Material.NETHERRACK
        ItemType.NETHER_BRICK -> Material.NETHER_BRICK
        ItemType.NETHER_BRICKS -> Material.NETHER_BRICKS
        ItemType.NETHER_BRICK_FENCE -> Material.NETHER_BRICK_FENCE
        ItemType.NETHER_BRICK_SLAB -> Material.NETHER_BRICK_SLAB
        ItemType.NETHER_BRICK_STAIRS -> Material.NETHER_BRICK_STAIRS
        ItemType.NETHER_PORTAL -> Material.NETHER_PORTAL
        ItemType.NETHER_QUARTZ_ORE -> Material.NETHER_QUARTZ_ORE
        ItemType.NETHER_STAR -> Material.NETHER_STAR
        ItemType.NETHER_WART -> Material.NETHER_WART
        ItemType.NETHER_WART_BLOCK -> Material.NETHER_WART_BLOCK
        ItemType.NOTE_BLOCK -> Material.NOTE_BLOCK
        ItemType.OAK_BOAT -> Material.OAK_BOAT
        ItemType.OAK_BUTTON -> Material.OAK_BUTTON
        ItemType.OAK_DOOR -> Material.OAK_DOOR
        ItemType.OAK_FENCE -> Material.OAK_FENCE
        ItemType.OAK_FENCE_GATE -> Material.OAK_FENCE_GATE
        ItemType.OAK_LEAVES -> Material.OAK_LEAVES
        ItemType.OAK_LOG -> Material.OAK_LOG
        ItemType.OAK_PLANKS -> Material.OAK_PLANKS
        ItemType.OAK_PRESSURE_PLATE -> Material.OAK_PRESSURE_PLATE
        ItemType.OAK_SAPLING -> Material.OAK_SAPLING
        ItemType.OAK_SLAB -> Material.OAK_SLAB
        ItemType.OAK_STAIRS -> Material.OAK_STAIRS
        ItemType.OAK_TRAPDOOR -> Material.OAK_TRAPDOOR
        ItemType.OAK_WOOD -> Material.OAK_WOOD
        ItemType.OBSERVER -> Material.OBSERVER
        ItemType.OBSIDIAN -> Material.OBSIDIAN
        ItemType.OCELOT_SPAWN_EGG -> Material.OCELOT_SPAWN_EGG
        ItemType.ORANGE_BANNER -> Material.ORANGE_BANNER
        ItemType.ORANGE_BED -> Material.ORANGE_BED
        ItemType.ORANGE_CARPET -> Material.ORANGE_CARPET
        ItemType.ORANGE_CONCRETE -> Material.ORANGE_CONCRETE
        ItemType.ORANGE_CONCRETE_POWDER -> Material.ORANGE_CONCRETE_POWDER
        ItemType.ORANGE_DYE -> Material.ORANGE_DYE
        ItemType.ORANGE_GLAZED_TERRACOTTA -> Material.ORANGE_GLAZED_TERRACOTTA
        ItemType.ORANGE_SHULKER_BOX -> Material.ORANGE_SHULKER_BOX
        ItemType.ORANGE_STAINED_GLASS -> Material.ORANGE_STAINED_GLASS
        ItemType.ORANGE_STAINED_GLASS_PANE -> Material.ORANGE_STAINED_GLASS_PANE
        ItemType.ORANGE_TERRACOTTA -> Material.ORANGE_TERRACOTTA
        ItemType.ORANGE_TULIP -> Material.ORANGE_TULIP
        ItemType.ORANGE_WALL_BANNER -> Material.ORANGE_WALL_BANNER
        ItemType.ORANGE_WOOL -> Material.ORANGE_WOOL
        ItemType.OXEYE_DAISY -> Material.OXEYE_DAISY
        ItemType.PACKED_ICE -> Material.PACKED_ICE
        ItemType.PAINTING -> Material.PAINTING
        ItemType.PAPER -> Material.PAPER
        ItemType.PARROT_SPAWN_EGG -> Material.PARROT_SPAWN_EGG
        ItemType.PEONY -> Material.PEONY
        ItemType.PETRIFIED_OAK_SLAB -> Material.PETRIFIED_OAK_SLAB
        ItemType.PHANTOM_MEMBRANE -> Material.PHANTOM_MEMBRANE
        ItemType.PHANTOM_SPAWN_EGG -> Material.PHANTOM_SPAWN_EGG
        ItemType.PIG_SPAWN_EGG -> Material.PIG_SPAWN_EGG
        ItemType.PINK_BANNER -> Material.PINK_BANNER
        ItemType.PINK_BED -> Material.PINK_BED
        ItemType.PINK_CARPET -> Material.PINK_CARPET
        ItemType.PINK_CONCRETE -> Material.PINK_CONCRETE
        ItemType.PINK_CONCRETE_POWDER -> Material.PINK_CONCRETE_POWDER
        ItemType.PINK_DYE -> Material.PINK_DYE
        ItemType.PINK_GLAZED_TERRACOTTA -> Material.PINK_GLAZED_TERRACOTTA
        ItemType.PINK_SHULKER_BOX -> Material.PINK_SHULKER_BOX
        ItemType.PINK_STAINED_GLASS -> Material.PINK_STAINED_GLASS
        ItemType.PINK_STAINED_GLASS_PANE -> Material.PINK_STAINED_GLASS_PANE
        ItemType.PINK_TERRACOTTA -> Material.PINK_TERRACOTTA
        ItemType.PINK_TULIP -> Material.PINK_TULIP
        ItemType.PINK_WALL_BANNER -> Material.PINK_WALL_BANNER
        ItemType.PINK_WOOL -> Material.PINK_WOOL
        ItemType.PISTON -> Material.PISTON
        ItemType.PISTON_HEAD -> Material.PISTON_HEAD
        ItemType.PLAYER_HEAD -> Material.PLAYER_HEAD
        ItemType.PLAYER_WALL_HEAD -> Material.PLAYER_WALL_HEAD
        ItemType.PODZOL -> Material.PODZOL
        ItemType.POISONOUS_POTATO -> Material.POISONOUS_POTATO
        ItemType.POLAR_BEAR_SPAWN_EGG -> Material.POLAR_BEAR_SPAWN_EGG
        ItemType.POLISHED_ANDESITE -> Material.POLISHED_ANDESITE
        ItemType.POLISHED_DIORITE -> Material.POLISHED_DIORITE
        ItemType.POLISHED_GRANITE -> Material.POLISHED_GRANITE
        ItemType.POPPED_CHORUS_FRUIT -> Material.POPPED_CHORUS_FRUIT
        ItemType.POPPY -> Material.POPPY
        ItemType.PORKCHOP -> Material.PORKCHOP
        ItemType.POTATO -> Material.POTATO
        ItemType.POTATOES -> Material.POTATOES
        ItemType.POTION -> Material.POTION
        ItemType.POTTED_ACACIA_SAPLING -> Material.POTTED_ACACIA_SAPLING
        ItemType.POTTED_ALLIUM -> Material.POTTED_ALLIUM
        ItemType.POTTED_AZURE_BLUET -> Material.POTTED_AZURE_BLUET
        ItemType.POTTED_BIRCH_SAPLING -> Material.POTTED_BIRCH_SAPLING
        ItemType.POTTED_BLUE_ORCHID -> Material.POTTED_BLUE_ORCHID
        ItemType.POTTED_BROWN_MUSHROOM -> Material.POTTED_BROWN_MUSHROOM
        ItemType.POTTED_CACTUS -> Material.POTTED_CACTUS
        ItemType.POTTED_DANDELION -> Material.POTTED_DANDELION
        ItemType.POTTED_DARK_OAK_SAPLING -> Material.POTTED_DARK_OAK_SAPLING
        ItemType.POTTED_DEAD_BUSH -> Material.POTTED_DEAD_BUSH
        ItemType.POTTED_FERN -> Material.POTTED_FERN
        ItemType.POTTED_JUNGLE_SAPLING -> Material.POTTED_JUNGLE_SAPLING
        ItemType.POTTED_OAK_SAPLING -> Material.POTTED_OAK_SAPLING
        ItemType.POTTED_ORANGE_TULIP -> Material.POTTED_ORANGE_TULIP
        ItemType.POTTED_OXEYE_DAISY -> Material.POTTED_OXEYE_DAISY
        ItemType.POTTED_PINK_TULIP -> Material.POTTED_PINK_TULIP
        ItemType.POTTED_POPPY -> Material.POTTED_POPPY
        ItemType.POTTED_RED_MUSHROOM -> Material.POTTED_RED_MUSHROOM
        ItemType.POTTED_RED_TULIP -> Material.POTTED_RED_TULIP
        ItemType.POTTED_SPRUCE_SAPLING -> Material.POTTED_SPRUCE_SAPLING
        ItemType.POTTED_WHITE_TULIP -> Material.POTTED_WHITE_TULIP
        ItemType.POWERED_RAIL -> Material.POWERED_RAIL
        ItemType.PRISMARINE -> Material.PRISMARINE
        ItemType.PRISMARINE_BRICKS -> Material.PRISMARINE_BRICKS
        ItemType.PRISMARINE_BRICK_SLAB -> Material.PRISMARINE_BRICK_SLAB
        ItemType.PRISMARINE_BRICK_STAIRS -> Material.PRISMARINE_BRICK_STAIRS
        ItemType.PRISMARINE_CRYSTALS -> Material.PRISMARINE_CRYSTALS
        ItemType.PRISMARINE_SHARD -> Material.PRISMARINE_SHARD
        ItemType.PRISMARINE_SLAB -> Material.PRISMARINE_SLAB
        ItemType.PRISMARINE_STAIRS -> Material.PRISMARINE_STAIRS
        ItemType.PUFFERFISH -> Material.PUFFERFISH
        ItemType.PUFFERFISH_BUCKET -> Material.PUFFERFISH_BUCKET
        ItemType.PUFFERFISH_SPAWN_EGG -> Material.PUFFERFISH_SPAWN_EGG
        ItemType.PUMPKIN -> Material.PUMPKIN
        ItemType.PUMPKIN_PIE -> Material.PUMPKIN_PIE
        ItemType.PUMPKIN_SEEDS -> Material.PUMPKIN_SEEDS
        ItemType.PUMPKIN_STEM -> Material.PUMPKIN_STEM
        ItemType.PURPLE_BANNER -> Material.PURPLE_BANNER
        ItemType.PURPLE_BED -> Material.PURPLE_BED
        ItemType.PURPLE_CARPET -> Material.PURPLE_CARPET
        ItemType.PURPLE_CONCRETE -> Material.PURPLE_CONCRETE
        ItemType.PURPLE_CONCRETE_POWDER -> Material.PURPLE_CONCRETE_POWDER
        ItemType.PURPLE_DYE -> Material.PURPLE_DYE
        ItemType.PURPLE_GLAZED_TERRACOTTA -> Material.PURPLE_GLAZED_TERRACOTTA
        ItemType.PURPLE_SHULKER_BOX -> Material.PURPLE_SHULKER_BOX
        ItemType.PURPLE_STAINED_GLASS -> Material.PURPLE_STAINED_GLASS
        ItemType.PURPLE_STAINED_GLASS_PANE -> Material.PURPLE_STAINED_GLASS_PANE
        ItemType.PURPLE_TERRACOTTA -> Material.PURPLE_TERRACOTTA
        ItemType.PURPLE_WALL_BANNER -> Material.PURPLE_WALL_BANNER
        ItemType.PURPLE_WOOL -> Material.PURPLE_WOOL
        ItemType.PURPUR_BLOCK -> Material.PURPUR_BLOCK
        ItemType.PURPUR_PILLAR -> Material.PURPUR_PILLAR
        ItemType.PURPUR_SLAB -> Material.PURPUR_SLAB
        ItemType.PURPUR_STAIRS -> Material.PURPUR_STAIRS
        ItemType.QUARTZ -> Material.QUARTZ
        ItemType.QUARTZ_BLOCK -> Material.QUARTZ_BLOCK
        ItemType.QUARTZ_PILLAR -> Material.QUARTZ_PILLAR
        ItemType.QUARTZ_SLAB -> Material.QUARTZ_SLAB
        ItemType.QUARTZ_STAIRS -> Material.QUARTZ_STAIRS
        ItemType.RABBIT -> Material.RABBIT
        ItemType.RABBIT_FOOT -> Material.RABBIT_FOOT
        ItemType.RABBIT_HIDE -> Material.RABBIT_HIDE
        ItemType.RABBIT_SPAWN_EGG -> Material.RABBIT_SPAWN_EGG
        ItemType.RABBIT_STEW -> Material.RABBIT_STEW
        ItemType.RAIL -> Material.RAIL
        ItemType.REDSTONE -> Material.REDSTONE
        ItemType.REDSTONE_BLOCK -> Material.REDSTONE_BLOCK
        ItemType.REDSTONE_LAMP -> Material.REDSTONE_LAMP
        ItemType.REDSTONE_ORE -> Material.REDSTONE_ORE
        ItemType.REDSTONE_TORCH -> Material.REDSTONE_TORCH
        ItemType.REDSTONE_WALL_TORCH -> Material.REDSTONE_WALL_TORCH
        ItemType.REDSTONE_WIRE -> Material.REDSTONE_WIRE
        ItemType.RED_BANNER -> Material.RED_BANNER
        ItemType.RED_BED -> Material.RED_BED
        ItemType.RED_CARPET -> Material.RED_CARPET
        ItemType.RED_CONCRETE -> Material.RED_CONCRETE
        ItemType.RED_CONCRETE_POWDER -> Material.RED_CONCRETE_POWDER
        ItemType.RED_GLAZED_TERRACOTTA -> Material.RED_GLAZED_TERRACOTTA
        ItemType.RED_MUSHROOM -> Material.RED_MUSHROOM
        ItemType.RED_MUSHROOM_BLOCK -> Material.RED_MUSHROOM_BLOCK
        ItemType.RED_NETHER_BRICKS -> Material.RED_NETHER_BRICKS
        ItemType.RED_SAND -> Material.RED_SAND
        ItemType.RED_SANDSTONE -> Material.RED_SANDSTONE
        ItemType.RED_SANDSTONE_SLAB -> Material.RED_SANDSTONE_SLAB
        ItemType.RED_SANDSTONE_STAIRS -> Material.RED_SANDSTONE_STAIRS
        ItemType.RED_SHULKER_BOX -> Material.RED_SHULKER_BOX
        ItemType.RED_STAINED_GLASS -> Material.RED_STAINED_GLASS
        ItemType.RED_STAINED_GLASS_PANE -> Material.RED_STAINED_GLASS_PANE
        ItemType.RED_TERRACOTTA -> Material.RED_TERRACOTTA
        ItemType.RED_TULIP -> Material.RED_TULIP
        ItemType.RED_WALL_BANNER -> Material.RED_WALL_BANNER
        ItemType.RED_WOOL -> Material.RED_WOOL
        ItemType.REPEATER -> Material.REPEATER
        ItemType.REPEATING_COMMAND_BLOCK -> Material.REPEATING_COMMAND_BLOCK
        ItemType.ROSE_BUSH -> Material.ROSE_BUSH
        ItemType.ROSE_RED -> Material.ROSE_RED
        ItemType.ROTTEN_FLESH -> Material.ROTTEN_FLESH
        ItemType.SADDLE -> Material.SADDLE
        ItemType.SALMON -> Material.SALMON
        ItemType.SALMON_BUCKET -> Material.SALMON_BUCKET
        ItemType.SALMON_SPAWN_EGG -> Material.SALMON_SPAWN_EGG
        ItemType.SAND -> Material.SAND
        ItemType.SANDSTONE -> Material.SANDSTONE
        ItemType.SANDSTONE_SLAB -> Material.SANDSTONE_SLAB
        ItemType.SANDSTONE_STAIRS -> Material.SANDSTONE_STAIRS
        ItemType.SCUTE -> Material.SCUTE
        ItemType.SEAGRASS -> Material.SEAGRASS
        ItemType.SEA_LANTERN -> Material.SEA_LANTERN
        ItemType.SEA_PICKLE -> Material.SEA_PICKLE
        ItemType.SHEARS -> Material.SHEARS
        ItemType.SHEEP_SPAWN_EGG -> Material.SHEEP_SPAWN_EGG
        ItemType.SHIELD -> Material.SHIELD
        ItemType.SHULKER_BOX -> Material.SHULKER_BOX
        ItemType.SHULKER_SHELL -> Material.SHULKER_SHELL
        ItemType.SHULKER_SPAWN_EGG -> Material.SHULKER_SPAWN_EGG
        ItemType.SIGN -> Material.SIGN
        ItemType.SILVERFISH_SPAWN_EGG -> Material.SILVERFISH_SPAWN_EGG
        ItemType.SKELETON_HORSE_SPAWN_EGG -> Material.SKELETON_HORSE_SPAWN_EGG
        ItemType.SKELETON_SKULL -> Material.SKELETON_SKULL
        ItemType.SKELETON_SPAWN_EGG -> Material.SKELETON_SPAWN_EGG
        ItemType.SKELETON_WALL_SKULL -> Material.SKELETON_WALL_SKULL
        ItemType.SLIME_BALL -> Material.SLIME_BALL
        ItemType.SLIME_BLOCK -> Material.SLIME_BLOCK
        ItemType.SLIME_SPAWN_EGG -> Material.SLIME_SPAWN_EGG
        ItemType.SMOOTH_QUARTZ -> Material.SMOOTH_QUARTZ
        ItemType.SMOOTH_RED_SANDSTONE -> Material.SMOOTH_RED_SANDSTONE
        ItemType.SMOOTH_SANDSTONE -> Material.SMOOTH_SANDSTONE
        ItemType.SMOOTH_STONE -> Material.SMOOTH_STONE
        ItemType.SNOW -> Material.SNOW
        ItemType.SNOWBALL -> Material.SNOWBALL
        ItemType.SNOW_BLOCK -> Material.SNOW_BLOCK
        ItemType.SOUL_SAND -> Material.SOUL_SAND
        ItemType.SPAWNER -> Material.SPAWNER
        ItemType.SPECTRAL_ARROW -> Material.SPECTRAL_ARROW
        ItemType.SPIDER_EYE -> Material.SPIDER_EYE
        ItemType.SPIDER_SPAWN_EGG -> Material.SPIDER_SPAWN_EGG
        ItemType.SPLASH_POTION -> Material.SPLASH_POTION
        ItemType.SPONGE -> Material.SPONGE
        ItemType.SPRUCE_BOAT -> Material.SPRUCE_BOAT
        ItemType.SPRUCE_BUTTON -> Material.SPRUCE_BUTTON
        ItemType.SPRUCE_DOOR -> Material.SPRUCE_DOOR
        ItemType.SPRUCE_FENCE -> Material.SPRUCE_FENCE
        ItemType.SPRUCE_FENCE_GATE -> Material.SPRUCE_FENCE_GATE
        ItemType.SPRUCE_LEAVES -> Material.SPRUCE_LEAVES
        ItemType.SPRUCE_LOG -> Material.SPRUCE_LOG
        ItemType.SPRUCE_PLANKS -> Material.SPRUCE_PLANKS
        ItemType.SPRUCE_PRESSURE_PLATE -> Material.SPRUCE_PRESSURE_PLATE
        ItemType.SPRUCE_SAPLING -> Material.SPRUCE_SAPLING
        ItemType.SPRUCE_SLAB -> Material.SPRUCE_SLAB
        ItemType.SPRUCE_STAIRS -> Material.SPRUCE_STAIRS
        ItemType.SPRUCE_TRAPDOOR -> Material.SPRUCE_TRAPDOOR
        ItemType.SPRUCE_WOOD -> Material.SPRUCE_WOOD
        ItemType.SQUID_SPAWN_EGG -> Material.SQUID_SPAWN_EGG
        ItemType.STICK -> Material.STICK
        ItemType.STICKY_PISTON -> Material.STICKY_PISTON
        ItemType.STONE -> Material.STONE
        ItemType.STONE_AXE -> Material.STONE_AXE
        ItemType.STONE_BRICKS -> Material.STONE_BRICKS
        ItemType.STONE_BRICK_SLAB -> Material.STONE_BRICK_SLAB
        ItemType.STONE_BRICK_STAIRS -> Material.STONE_BRICK_STAIRS
        ItemType.STONE_BUTTON -> Material.STONE_BUTTON
        ItemType.STONE_HOE -> Material.STONE_HOE
        ItemType.STONE_PICKAXE -> Material.STONE_PICKAXE
        ItemType.STONE_PRESSURE_PLATE -> Material.STONE_PRESSURE_PLATE
        ItemType.STONE_SHOVEL -> Material.STONE_SHOVEL
        ItemType.STONE_SLAB -> Material.STONE_SLAB
        ItemType.STONE_SWORD -> Material.STONE_SWORD
        ItemType.STRAY_SPAWN_EGG -> Material.STRAY_SPAWN_EGG
        ItemType.STRING -> Material.STRING
        ItemType.STRIPPED_ACACIA_LOG -> Material.STRIPPED_ACACIA_LOG
        ItemType.STRIPPED_ACACIA_WOOD -> Material.STRIPPED_ACACIA_WOOD
        ItemType.STRIPPED_BIRCH_LOG -> Material.STRIPPED_BIRCH_LOG
        ItemType.STRIPPED_BIRCH_WOOD -> Material.STRIPPED_BIRCH_WOOD
        ItemType.STRIPPED_DARK_OAK_LOG -> Material.STRIPPED_DARK_OAK_LOG
        ItemType.STRIPPED_DARK_OAK_WOOD -> Material.STRIPPED_DARK_OAK_WOOD
        ItemType.STRIPPED_JUNGLE_LOG -> Material.STRIPPED_JUNGLE_LOG
        ItemType.STRIPPED_JUNGLE_WOOD -> Material.STRIPPED_JUNGLE_WOOD
        ItemType.STRIPPED_OAK_LOG -> Material.STRIPPED_OAK_LOG
        ItemType.STRIPPED_OAK_WOOD -> Material.STRIPPED_OAK_WOOD
        ItemType.STRIPPED_SPRUCE_LOG -> Material.STRIPPED_SPRUCE_LOG
        ItemType.STRIPPED_SPRUCE_WOOD -> Material.STRIPPED_SPRUCE_WOOD
        ItemType.STRUCTURE_BLOCK -> Material.STRUCTURE_BLOCK
        ItemType.STRUCTURE_VOID -> Material.STRUCTURE_VOID
        ItemType.SUGAR -> Material.SUGAR
        ItemType.SUGAR_CANE -> Material.SUGAR_CANE
        ItemType.SUNFLOWER -> Material.SUNFLOWER
        ItemType.TALL_GRASS -> Material.TALL_GRASS
        ItemType.TALL_SEAGRASS -> Material.TALL_SEAGRASS
        ItemType.TERRACOTTA -> Material.TERRACOTTA
        ItemType.TIPPED_ARROW -> Material.TIPPED_ARROW
        ItemType.TNT -> Material.TNT
        ItemType.TNT_MINECART -> Material.TNT_MINECART
        ItemType.TORCH -> Material.TORCH
        ItemType.TOTEM_OF_UNDYING -> Material.TOTEM_OF_UNDYING
        ItemType.TRAPPED_CHEST -> Material.TRAPPED_CHEST
        ItemType.TRIDENT -> Material.TRIDENT
        ItemType.TRIPWIRE -> Material.TRIPWIRE
        ItemType.TRIPWIRE_HOOK -> Material.TRIPWIRE_HOOK
        ItemType.TROPICAL_FISH -> Material.TROPICAL_FISH
        ItemType.TROPICAL_FISH_BUCKET -> Material.TROPICAL_FISH_BUCKET
        ItemType.TROPICAL_FISH_SPAWN_EGG -> Material.TROPICAL_FISH_SPAWN_EGG
        ItemType.TUBE_CORAL -> Material.TUBE_CORAL
        ItemType.TUBE_CORAL_BLOCK -> Material.TUBE_CORAL_BLOCK
        ItemType.TUBE_CORAL_FAN -> Material.TUBE_CORAL_FAN
        ItemType.TUBE_CORAL_WALL_FAN -> Material.TUBE_CORAL_WALL_FAN
        ItemType.TURTLE_EGG -> Material.TURTLE_EGG
        ItemType.TURTLE_HELMET -> Material.TURTLE_HELMET
        ItemType.TURTLE_SPAWN_EGG -> Material.TURTLE_SPAWN_EGG
        ItemType.VEX_SPAWN_EGG -> Material.VEX_SPAWN_EGG
        ItemType.VILLAGER_SPAWN_EGG -> Material.VILLAGER_SPAWN_EGG
        ItemType.VINDICATOR_SPAWN_EGG -> Material.VINDICATOR_SPAWN_EGG
        ItemType.VINE -> Material.VINE
        ItemType.VOID_AIR -> Material.VOID_AIR
        ItemType.WALL_SIGN -> Material.WALL_SIGN
        ItemType.WALL_TORCH -> Material.WALL_TORCH
        ItemType.WATER -> Material.WATER
        ItemType.WATER_BUCKET -> Material.WATER_BUCKET
        ItemType.WET_SPONGE -> Material.WET_SPONGE
        ItemType.WHEAT -> Material.WHEAT
        ItemType.WHEAT_SEEDS -> Material.WHEAT_SEEDS
        ItemType.WHITE_BANNER -> Material.WHITE_BANNER
        ItemType.WHITE_BED -> Material.WHITE_BED
        ItemType.WHITE_CARPET -> Material.WHITE_CARPET
        ItemType.WHITE_CONCRETE -> Material.WHITE_CONCRETE
        ItemType.WHITE_CONCRETE_POWDER -> Material.WHITE_CONCRETE_POWDER
        ItemType.WHITE_GLAZED_TERRACOTTA -> Material.WHITE_GLAZED_TERRACOTTA
        ItemType.WHITE_SHULKER_BOX -> Material.WHITE_SHULKER_BOX
        ItemType.WHITE_STAINED_GLASS -> Material.WHITE_STAINED_GLASS
        ItemType.WHITE_STAINED_GLASS_PANE -> Material.WHITE_STAINED_GLASS_PANE
        ItemType.WHITE_TERRACOTTA -> Material.WHITE_TERRACOTTA
        ItemType.WHITE_TULIP -> Material.WHITE_TULIP
        ItemType.WHITE_WALL_BANNER -> Material.WHITE_WALL_BANNER
        ItemType.WHITE_WOOL -> Material.WHITE_WOOL
        ItemType.WITCH_SPAWN_EGG -> Material.WITCH_SPAWN_EGG
        ItemType.WITHER_SKELETON_SKULL -> Material.WITHER_SKELETON_SKULL
        ItemType.WITHER_SKELETON_SPAWN_EGG -> Material.WITHER_SKELETON_SPAWN_EGG
        ItemType.WITHER_SKELETON_WALL_SKULL -> Material.WITHER_SKELETON_WALL_SKULL
        ItemType.WOLF_SPAWN_EGG -> Material.WOLF_SPAWN_EGG
        ItemType.WOODEN_AXE -> Material.WOODEN_AXE
        ItemType.WOODEN_HOE -> Material.WOODEN_HOE
        ItemType.WOODEN_PICKAXE -> Material.WOODEN_PICKAXE
        ItemType.WOODEN_SHOVEL -> Material.WOODEN_SHOVEL
        ItemType.WOODEN_SWORD -> Material.WOODEN_SWORD
        ItemType.WRITABLE_BOOK -> Material.WRITABLE_BOOK
        ItemType.WRITTEN_BOOK -> Material.WRITTEN_BOOK
        ItemType.YELLOW_BANNER -> Material.YELLOW_BANNER
        ItemType.YELLOW_BED -> Material.YELLOW_BED
        ItemType.YELLOW_CARPET -> Material.YELLOW_CARPET
        ItemType.YELLOW_CONCRETE -> Material.YELLOW_CONCRETE
        ItemType.YELLOW_CONCRETE_POWDER -> Material.YELLOW_CONCRETE_POWDER
        ItemType.YELLOW_GLAZED_TERRACOTTA -> Material.YELLOW_GLAZED_TERRACOTTA
        ItemType.YELLOW_SHULKER_BOX -> Material.YELLOW_SHULKER_BOX
        ItemType.YELLOW_STAINED_GLASS -> Material.YELLOW_STAINED_GLASS
        ItemType.YELLOW_STAINED_GLASS_PANE -> Material.YELLOW_STAINED_GLASS_PANE
        ItemType.YELLOW_TERRACOTTA -> Material.YELLOW_TERRACOTTA
        ItemType.YELLOW_WALL_BANNER -> Material.YELLOW_WALL_BANNER
        ItemType.YELLOW_WOOL -> Material.YELLOW_WOOL
        ItemType.ZOMBIE_HEAD -> Material.ZOMBIE_HEAD
        ItemType.ZOMBIE_HORSE_SPAWN_EGG -> Material.ZOMBIE_HORSE_SPAWN_EGG
        ItemType.ZOMBIE_PIGMAN_SPAWN_EGG -> Material.ZOMBIE_PIGMAN_SPAWN_EGG
        ItemType.ZOMBIE_SPAWN_EGG -> Material.ZOMBIE_SPAWN_EGG
        ItemType.ZOMBIE_VILLAGER_SPAWN_EGG -> Material.ZOMBIE_VILLAGER_SPAWN_EGG
        ItemType.ZOMBIE_WALL_HEAD -> Material.ZOMBIE_WALL_HEAD
    }
}