package net.craftlin.plugin.bukkit.impl.value

import net.craftlin.plugin.api.value.EnumValue
import org.bukkit.Material

object BukkitMaterial: EnumValue<Material>() {

    override val values = mapOf(
        "acacia boat" to Material.ACACIA_BOAT,
        "acacia button" to Material.ACACIA_BUTTON,
        "acacia door" to Material.ACACIA_DOOR,
        "acacia fence" to Material.ACACIA_FENCE,
        "acacia fence gate" to Material.ACACIA_FENCE_GATE,
        "acacia leaves" to Material.ACACIA_LEAVES,
        "acacia log" to Material.ACACIA_LOG,
        "acacia planks" to Material.ACACIA_PLANKS,
        "acacia pressure plate" to Material.ACACIA_PRESSURE_PLATE,
        "acacia sapling" to Material.ACACIA_SAPLING,
        "acacia slab" to Material.ACACIA_SLAB,
        "acacia stairs" to Material.ACACIA_STAIRS,
        "acacia trapdoor" to Material.ACACIA_TRAPDOOR,
        "acacia wood" to Material.ACACIA_WOOD,
        "activator rail" to Material.ACTIVATOR_RAIL,
        "air" to Material.AIR,
        "allium" to Material.ALLIUM,
        "andesite" to Material.ANDESITE,
        "anvil" to Material.ANVIL,
        "apple" to Material.APPLE,
        "armor stand" to Material.ARMOR_STAND,
        "arrow" to Material.ARROW,
        "attached melon stem" to Material.ATTACHED_MELON_STEM,
        "attached pumpkin stem" to Material.ATTACHED_PUMPKIN_STEM,
        "azure bluet" to Material.AZURE_BLUET,
        "baked potato" to Material.BAKED_POTATO,
        "barrier" to Material.BARRIER,
        "bat spawn egg" to Material.BAT_SPAWN_EGG,
        "beacon" to Material.BEACON,
        "bedrock" to Material.BEDROCK,
        "beef" to Material.BEEF,
        "beetroot" to Material.BEETROOT,
        "beetroots" to Material.BEETROOTS,
        "beetroot seeds" to Material.BEETROOT_SEEDS,
        "beetroot soup" to Material.BEETROOT_SOUP,
        "birch boat" to Material.BIRCH_BOAT,
        "birch button" to Material.BIRCH_BUTTON,
        "birch door" to Material.BIRCH_DOOR,
        "birch fence" to Material.BIRCH_FENCE,
        "birch fence gate" to Material.BIRCH_FENCE_GATE,
        "birch leaves" to Material.BIRCH_LEAVES,
        "birch log" to Material.BIRCH_LOG,
        "birch planks" to Material.BIRCH_PLANKS,
        "birch pressure plate" to Material.BIRCH_PRESSURE_PLATE,
        "birch sapling" to Material.BIRCH_SAPLING,
        "birch slab" to Material.BIRCH_SLAB,
        "birch stairs" to Material.BIRCH_STAIRS,
        "birch trapdoor" to Material.BIRCH_TRAPDOOR,
        "birch wood" to Material.BIRCH_WOOD,
        "black banner" to Material.BLACK_BANNER,
        "black bed" to Material.BLACK_BED,
        "black carpet" to Material.BLACK_CARPET,
        "black concrete" to Material.BLACK_CONCRETE,
        "black concrete powder" to Material.BLACK_CONCRETE_POWDER,
        "black glazed terracotta" to Material.BLACK_GLAZED_TERRACOTTA,
        "black shulker box" to Material.BLACK_SHULKER_BOX,
        "black stained glass" to Material.BLACK_STAINED_GLASS,
        "black stained glass pane" to Material.BLACK_STAINED_GLASS_PANE,
        "black terracotta" to Material.BLACK_TERRACOTTA,
        "black wall banner" to Material.BLACK_WALL_BANNER,
        "black wool" to Material.BLACK_WOOL,
        "blaze powder" to Material.BLAZE_POWDER,
        "blaze rod" to Material.BLAZE_ROD,
        "blaze spawn egg" to Material.BLAZE_SPAWN_EGG,
        "blue banner" to Material.BLUE_BANNER,
        "blue bed" to Material.BLUE_BED,
        "blue carpet" to Material.BLUE_CARPET,
        "blue concrete" to Material.BLUE_CONCRETE,
        "blue concrete powder" to Material.BLUE_CONCRETE_POWDER,
        "blue glazed terracotta" to Material.BLUE_GLAZED_TERRACOTTA,
        "blue ice" to Material.BLUE_ICE,
        "blue orchid" to Material.BLUE_ORCHID,
        "blue shulker box" to Material.BLUE_SHULKER_BOX,
        "blue stained glass" to Material.BLUE_STAINED_GLASS,
        "blue stained glass pane" to Material.BLUE_STAINED_GLASS_PANE,
        "blue terracotta" to Material.BLUE_TERRACOTTA,
        "blue wall banner" to Material.BLUE_WALL_BANNER,
        "blue wool" to Material.BLUE_WOOL,
        "bone" to Material.BONE,
        "bone block" to Material.BONE_BLOCK,
        "bone meal" to Material.BONE_MEAL,
        "book" to Material.BOOK,
        "bookshelf" to Material.BOOKSHELF,
        "bow" to Material.BOW,
        "bowl" to Material.BOWL,
        "brain coral" to Material.BRAIN_CORAL,
        "brain coral block" to Material.BRAIN_CORAL_BLOCK,
        "brain coral fan" to Material.BRAIN_CORAL_FAN,
        "brain coral wall fan" to Material.BRAIN_CORAL_WALL_FAN,
        "bread" to Material.BREAD,
        "brewing stand" to Material.BREWING_STAND,
        "brick" to Material.BRICK,
        "bricks" to Material.BRICKS,
        "brick slab" to Material.BRICK_SLAB,
        "brick stairs" to Material.BRICK_STAIRS,
        "brown banner" to Material.BROWN_BANNER,
        "brown bed" to Material.BROWN_BED,
        "brown carpet" to Material.BROWN_CARPET,
        "brown concrete" to Material.BROWN_CONCRETE,
        "brown concrete powder" to Material.BROWN_CONCRETE_POWDER,
        "brown glazed terracotta" to Material.BROWN_GLAZED_TERRACOTTA,
        "brown mushroom" to Material.BROWN_MUSHROOM,
        "brown mushroom block" to Material.BROWN_MUSHROOM_BLOCK,
        "brown shulker box" to Material.BROWN_SHULKER_BOX,
        "brown stained glass" to Material.BROWN_STAINED_GLASS,
        "brown stained glass pane" to Material.BROWN_STAINED_GLASS_PANE,
        "brown terracotta" to Material.BROWN_TERRACOTTA,
        "brown wall banner" to Material.BROWN_WALL_BANNER,
        "brown wool" to Material.BROWN_WOOL,
        "bubble column" to Material.BUBBLE_COLUMN,
        "bubble coral" to Material.BUBBLE_CORAL,
        "bubble coral block" to Material.BUBBLE_CORAL_BLOCK,
        "bubble coral fan" to Material.BUBBLE_CORAL_FAN,
        "bubble coral wall fan" to Material.BUBBLE_CORAL_WALL_FAN,
        "bucket" to Material.BUCKET,
        "cactus" to Material.CACTUS,
        "cactus green" to Material.CACTUS_GREEN,
        "cake" to Material.CAKE,
        "carrot" to Material.CARROT,
        "carrots" to Material.CARROTS,
        "carrot on a stick" to Material.CARROT_ON_A_STICK,
        "carved pumpkin" to Material.CARVED_PUMPKIN,
        "cauldron" to Material.CAULDRON,
        "cave air" to Material.CAVE_AIR,
        "cave spider spawn egg" to Material.CAVE_SPIDER_SPAWN_EGG,
        "chainmail boots" to Material.CHAINMAIL_BOOTS,
        "chainmail chestplate" to Material.CHAINMAIL_CHESTPLATE,
        "chainmail helmet" to Material.CHAINMAIL_HELMET,
        "chainmail leggings" to Material.CHAINMAIL_LEGGINGS,
        "chain command block" to Material.CHAIN_COMMAND_BLOCK,
        "charcoal" to Material.CHARCOAL,
        "chest" to Material.CHEST,
        "chest minecart" to Material.CHEST_MINECART,
        "chicken" to Material.CHICKEN,
        "chicken spawn egg" to Material.CHICKEN_SPAWN_EGG,
        "chipped anvil" to Material.CHIPPED_ANVIL,
        "chiseled quartz block" to Material.CHISELED_QUARTZ_BLOCK,
        "chiseled red sandstone" to Material.CHISELED_RED_SANDSTONE,
        "chiseled sandstone" to Material.CHISELED_SANDSTONE,
        "chiseled stone bricks" to Material.CHISELED_STONE_BRICKS,
        "chorus flower" to Material.CHORUS_FLOWER,
        "chorus fruit" to Material.CHORUS_FRUIT,
        "chorus plant" to Material.CHORUS_PLANT,
        "clay" to Material.CLAY,
        "clay ball" to Material.CLAY_BALL,
        "clock" to Material.CLOCK,
        "coal" to Material.COAL,
        "coal block" to Material.COAL_BLOCK,
        "coal ore" to Material.COAL_ORE,
        "coarse dirt" to Material.COARSE_DIRT,
        "cobblestone" to Material.COBBLESTONE,
        "cobblestone slab" to Material.COBBLESTONE_SLAB,
        "cobblestone stairs" to Material.COBBLESTONE_STAIRS,
        "cobblestone wall" to Material.COBBLESTONE_WALL,
        "cobweb" to Material.COBWEB,
        "cocoa" to Material.COCOA,
        "cocoa beans" to Material.COCOA_BEANS,
        "cod" to Material.COD,
        "cod bucket" to Material.COD_BUCKET,
        "cod spawn egg" to Material.COD_SPAWN_EGG,
        "command block" to Material.COMMAND_BLOCK,
        "command block minecart" to Material.COMMAND_BLOCK_MINECART,
        "comparator" to Material.COMPARATOR,
        "compass" to Material.COMPASS,
        "conduit" to Material.CONDUIT,
        "cooked beef" to Material.COOKED_BEEF,
        "cooked chicken" to Material.COOKED_CHICKEN,
        "cooked cod" to Material.COOKED_COD,
        "cooked mutton" to Material.COOKED_MUTTON,
        "cooked porkchop" to Material.COOKED_PORKCHOP,
        "cooked rabbit" to Material.COOKED_RABBIT,
        "cooked salmon" to Material.COOKED_SALMON,
        "cookie" to Material.COOKIE,
        "cow spawn egg" to Material.COW_SPAWN_EGG,
        "cracked stone bricks" to Material.CRACKED_STONE_BRICKS,
        "crafting table" to Material.CRAFTING_TABLE,
        "creeper head" to Material.CREEPER_HEAD,
        "creeper spawn egg" to Material.CREEPER_SPAWN_EGG,
        "creeper wall head" to Material.CREEPER_WALL_HEAD,
        "cut red sandstone" to Material.CUT_RED_SANDSTONE,
        "cut sandstone" to Material.CUT_SANDSTONE,
        "cyan banner" to Material.CYAN_BANNER,
        "cyan bed" to Material.CYAN_BED,
        "cyan carpet" to Material.CYAN_CARPET,
        "cyan concrete" to Material.CYAN_CONCRETE,
        "cyan concrete powder" to Material.CYAN_CONCRETE_POWDER,
        "cyan dye" to Material.CYAN_DYE,
        "cyan glazed terracotta" to Material.CYAN_GLAZED_TERRACOTTA,
        "cyan shulker box" to Material.CYAN_SHULKER_BOX,
        "cyan stained glass" to Material.CYAN_STAINED_GLASS,
        "cyan stained glass pane" to Material.CYAN_STAINED_GLASS_PANE,
        "cyan terracotta" to Material.CYAN_TERRACOTTA,
        "cyan wall banner" to Material.CYAN_WALL_BANNER,
        "cyan wool" to Material.CYAN_WOOL,
        "damaged anvil" to Material.DAMAGED_ANVIL,
        "dandelion" to Material.DANDELION,
        "dandelion yellow" to Material.DANDELION_YELLOW,
        "dark oak boat" to Material.DARK_OAK_BOAT,
        "dark oak button" to Material.DARK_OAK_BUTTON,
        "dark oak door" to Material.DARK_OAK_DOOR,
        "dark oak fence" to Material.DARK_OAK_FENCE,
        "dark oak fence gate" to Material.DARK_OAK_FENCE_GATE,
        "dark oak leaves" to Material.DARK_OAK_LEAVES,
        "dark oak log" to Material.DARK_OAK_LOG,
        "dark oak planks" to Material.DARK_OAK_PLANKS,
        "dark oak pressure plate" to Material.DARK_OAK_PRESSURE_PLATE,
        "dark oak sapling" to Material.DARK_OAK_SAPLING,
        "dark oak slab" to Material.DARK_OAK_SLAB,
        "dark oak stairs" to Material.DARK_OAK_STAIRS,
        "dark oak trapdoor" to Material.DARK_OAK_TRAPDOOR,
        "dark oak wood" to Material.DARK_OAK_WOOD,
        "dark prismarine" to Material.DARK_PRISMARINE,
        "dark prismarine slab" to Material.DARK_PRISMARINE_SLAB,
        "dark prismarine stairs" to Material.DARK_PRISMARINE_STAIRS,
        "daylight detector" to Material.DAYLIGHT_DETECTOR,
        "dead brain coral block" to Material.DEAD_BRAIN_CORAL_BLOCK,
        "dead brain coral fan" to Material.DEAD_BRAIN_CORAL_FAN,
        "dead brain coral wall fan" to Material.DEAD_BRAIN_CORAL_WALL_FAN,
        "dead bubble coral block" to Material.DEAD_BUBBLE_CORAL_BLOCK,
        "dead bubble coral fan" to Material.DEAD_BUBBLE_CORAL_FAN,
        "dead bubble coral wall fan" to Material.DEAD_BUBBLE_CORAL_WALL_FAN,
        "dead bush" to Material.DEAD_BUSH,
        "dead fire coral block" to Material.DEAD_FIRE_CORAL_BLOCK,
        "dead fire coral fan" to Material.DEAD_FIRE_CORAL_FAN,
        "dead fire coral wall fan" to Material.DEAD_FIRE_CORAL_WALL_FAN,
        "dead horn coral block" to Material.DEAD_HORN_CORAL_BLOCK,
        "dead horn coral fan" to Material.DEAD_HORN_CORAL_FAN,
        "dead horn coral wall fan" to Material.DEAD_HORN_CORAL_WALL_FAN,
        "dead tube coral block" to Material.DEAD_TUBE_CORAL_BLOCK,
        "dead tube coral fan" to Material.DEAD_TUBE_CORAL_FAN,
        "dead tube coral wall fan" to Material.DEAD_TUBE_CORAL_WALL_FAN,
        "debug stick" to Material.DEBUG_STICK,
        "detector rail" to Material.DETECTOR_RAIL,
        "diamond" to Material.DIAMOND,
        "diamond axe" to Material.DIAMOND_AXE,
        "diamond block" to Material.DIAMOND_BLOCK,
        "diamond boots" to Material.DIAMOND_BOOTS,
        "diamond chestplate" to Material.DIAMOND_CHESTPLATE,
        "diamond helmet" to Material.DIAMOND_HELMET,
        "diamond hoe" to Material.DIAMOND_HOE,
        "diamond horse armor" to Material.DIAMOND_HORSE_ARMOR,
        "diamond leggings" to Material.DIAMOND_LEGGINGS,
        "diamond ore" to Material.DIAMOND_ORE,
        "diamond pickaxe" to Material.DIAMOND_PICKAXE,
        "diamond shovel" to Material.DIAMOND_SHOVEL,
        "diamond sword" to Material.DIAMOND_SWORD,
        "diorite" to Material.DIORITE,
        "dirt" to Material.DIRT,
        "dispenser" to Material.DISPENSER,
        "dolphin spawn egg" to Material.DOLPHIN_SPAWN_EGG,
        "donkey spawn egg" to Material.DONKEY_SPAWN_EGG,
        "dragon breath" to Material.DRAGON_BREATH,
        "dragon egg" to Material.DRAGON_EGG,
        "dragon head" to Material.DRAGON_HEAD,
        "dragon wall head" to Material.DRAGON_WALL_HEAD,
        "dried kelp" to Material.DRIED_KELP,
        "dried kelp block" to Material.DRIED_KELP_BLOCK,
        "dropper" to Material.DROPPER,
        "drowned spawn egg" to Material.DROWNED_SPAWN_EGG,
        "egg" to Material.EGG,
        "elder guardian spawn egg" to Material.ELDER_GUARDIAN_SPAWN_EGG,
        "elytra" to Material.ELYTRA,
        "emerald" to Material.EMERALD,
        "emerald block" to Material.EMERALD_BLOCK,
        "emerald ore" to Material.EMERALD_ORE,
        "enchanted book" to Material.ENCHANTED_BOOK,
        "enchanted golden apple" to Material.ENCHANTED_GOLDEN_APPLE,
        "enchanting table" to Material.ENCHANTING_TABLE,
        "enderman spawn egg" to Material.ENDERMAN_SPAWN_EGG,
        "endermite spawn egg" to Material.ENDERMITE_SPAWN_EGG,
        "ender chest" to Material.ENDER_CHEST,
        "ender eye" to Material.ENDER_EYE,
        "ender pearl" to Material.ENDER_PEARL,
        "end crystal" to Material.END_CRYSTAL,
        "end gateway" to Material.END_GATEWAY,
        "end portal" to Material.END_PORTAL,
        "end portal frame" to Material.END_PORTAL_FRAME,
        "end rod" to Material.END_ROD,
        "end stone" to Material.END_STONE,
        "end stone bricks" to Material.END_STONE_BRICKS,
        "evoker spawn egg" to Material.EVOKER_SPAWN_EGG,
        "experience bottle" to Material.EXPERIENCE_BOTTLE,
        "farmland" to Material.FARMLAND,
        "feather" to Material.FEATHER,
        "fermented spider eye" to Material.FERMENTED_SPIDER_EYE,
        "fern" to Material.FERN,
        "filled map" to Material.FILLED_MAP,
        "fire" to Material.FIRE,
        "firework rocket" to Material.FIREWORK_ROCKET,
        "firework star" to Material.FIREWORK_STAR,
        "fire charge" to Material.FIRE_CHARGE,
        "fire coral" to Material.FIRE_CORAL,
        "fire coral block" to Material.FIRE_CORAL_BLOCK,
        "fire coral fan" to Material.FIRE_CORAL_FAN,
        "fire coral wall fan" to Material.FIRE_CORAL_WALL_FAN,
        "fishing rod" to Material.FISHING_ROD,
        "flint" to Material.FLINT,
        "flint and steel" to Material.FLINT_AND_STEEL,
        "flower pot" to Material.FLOWER_POT,
        "frosted ice" to Material.FROSTED_ICE,
        "furnace" to Material.FURNACE,
        "furnace minecart" to Material.FURNACE_MINECART,
        "ghast spawn egg" to Material.GHAST_SPAWN_EGG,
        "ghast tear" to Material.GHAST_TEAR,
        "glass" to Material.GLASS,
        "glass bottle" to Material.GLASS_BOTTLE,
        "glass pane" to Material.GLASS_PANE,
        "glistering melon slice" to Material.GLISTERING_MELON_SLICE,
        "glowstone" to Material.GLOWSTONE,
        "glowstone dust" to Material.GLOWSTONE_DUST,
        "golden apple" to Material.GOLDEN_APPLE,
        "golden axe" to Material.GOLDEN_AXE,
        "golden boots" to Material.GOLDEN_BOOTS,
        "golden carrot" to Material.GOLDEN_CARROT,
        "golden chestplate" to Material.GOLDEN_CHESTPLATE,
        "golden helmet" to Material.GOLDEN_HELMET,
        "golden hoe" to Material.GOLDEN_HOE,
        "golden horse armor" to Material.GOLDEN_HORSE_ARMOR,
        "golden leggings" to Material.GOLDEN_LEGGINGS,
        "golden pickaxe" to Material.GOLDEN_PICKAXE,
        "golden shovel" to Material.GOLDEN_SHOVEL,
        "golden sword" to Material.GOLDEN_SWORD,
        "gold block" to Material.GOLD_BLOCK,
        "gold ingot" to Material.GOLD_INGOT,
        "gold nugget" to Material.GOLD_NUGGET,
        "gold ore" to Material.GOLD_ORE,
        "granite" to Material.GRANITE,
        "grass" to Material.GRASS,
        "grass block" to Material.GRASS_BLOCK,
        "grass path" to Material.GRASS_PATH,
        "gravel" to Material.GRAVEL,
        "gray banner" to Material.GRAY_BANNER,
        "gray bed" to Material.GRAY_BED,
        "gray carpet" to Material.GRAY_CARPET,
        "gray concrete" to Material.GRAY_CONCRETE,
        "gray concrete powder" to Material.GRAY_CONCRETE_POWDER,
        "gray dye" to Material.GRAY_DYE,
        "gray glazed terracotta" to Material.GRAY_GLAZED_TERRACOTTA,
        "gray shulker box" to Material.GRAY_SHULKER_BOX,
        "gray stained glass" to Material.GRAY_STAINED_GLASS,
        "gray stained glass pane" to Material.GRAY_STAINED_GLASS_PANE,
        "gray terracotta" to Material.GRAY_TERRACOTTA,
        "gray wall banner" to Material.GRAY_WALL_BANNER,
        "gray wool" to Material.GRAY_WOOL,
        "green banner" to Material.GREEN_BANNER,
        "green bed" to Material.GREEN_BED,
        "green carpet" to Material.GREEN_CARPET,
        "green concrete" to Material.GREEN_CONCRETE,
        "green concrete powder" to Material.GREEN_CONCRETE_POWDER,
        "green glazed terracotta" to Material.GREEN_GLAZED_TERRACOTTA,
        "green shulker box" to Material.GREEN_SHULKER_BOX,
        "green stained glass" to Material.GREEN_STAINED_GLASS,
        "green stained glass pane" to Material.GREEN_STAINED_GLASS_PANE,
        "green terracotta" to Material.GREEN_TERRACOTTA,
        "green wall banner" to Material.GREEN_WALL_BANNER,
        "green wool" to Material.GREEN_WOOL,
        "guardian spawn egg" to Material.GUARDIAN_SPAWN_EGG,
        "gunpowder" to Material.GUNPOWDER,
        "hay block" to Material.HAY_BLOCK,
        "heart of the sea" to Material.HEART_OF_THE_SEA,
        "heavy weighted pressure plate" to Material.HEAVY_WEIGHTED_PRESSURE_PLATE,
        "hopper" to Material.HOPPER,
        "hopper minecart" to Material.HOPPER_MINECART,
        "horn coral" to Material.HORN_CORAL,
        "horn coral block" to Material.HORN_CORAL_BLOCK,
        "horn coral fan" to Material.HORN_CORAL_FAN,
        "horn coral wall fan" to Material.HORN_CORAL_WALL_FAN,
        "horse spawn egg" to Material.HORSE_SPAWN_EGG,
        "husk spawn egg" to Material.HUSK_SPAWN_EGG,
        "ice" to Material.ICE,
        "infested chiseled stone bricks" to Material.INFESTED_CHISELED_STONE_BRICKS,
        "infested cobblestone" to Material.INFESTED_COBBLESTONE,
        "infested cracked stone bricks" to Material.INFESTED_CRACKED_STONE_BRICKS,
        "infested mossy stone bricks" to Material.INFESTED_MOSSY_STONE_BRICKS,
        "infested stone" to Material.INFESTED_STONE,
        "infested stone bricks" to Material.INFESTED_STONE_BRICKS,
        "ink sac" to Material.INK_SAC,
        "iron axe" to Material.IRON_AXE,
        "iron bars" to Material.IRON_BARS,
        "iron block" to Material.IRON_BLOCK,
        "iron boots" to Material.IRON_BOOTS,
        "iron chestplate" to Material.IRON_CHESTPLATE,
        "iron door" to Material.IRON_DOOR,
        "iron helmet" to Material.IRON_HELMET,
        "iron hoe" to Material.IRON_HOE,
        "iron horse armor" to Material.IRON_HORSE_ARMOR,
        "iron ingot" to Material.IRON_INGOT,
        "iron leggings" to Material.IRON_LEGGINGS,
        "iron nugget" to Material.IRON_NUGGET,
        "iron ore" to Material.IRON_ORE,
        "iron pickaxe" to Material.IRON_PICKAXE,
        "iron shovel" to Material.IRON_SHOVEL,
        "iron sword" to Material.IRON_SWORD,
        "iron trapdoor" to Material.IRON_TRAPDOOR,
        "item frame" to Material.ITEM_FRAME,
        "jack o lantern" to Material.JACK_O_LANTERN,
        "jukebox" to Material.JUKEBOX,
        "jungle boat" to Material.JUNGLE_BOAT,
        "jungle button" to Material.JUNGLE_BUTTON,
        "jungle door" to Material.JUNGLE_DOOR,
        "jungle fence" to Material.JUNGLE_FENCE,
        "jungle fence gate" to Material.JUNGLE_FENCE_GATE,
        "jungle leaves" to Material.JUNGLE_LEAVES,
        "jungle log" to Material.JUNGLE_LOG,
        "jungle planks" to Material.JUNGLE_PLANKS,
        "jungle pressure plate" to Material.JUNGLE_PRESSURE_PLATE,
        "jungle sapling" to Material.JUNGLE_SAPLING,
        "jungle slab" to Material.JUNGLE_SLAB,
        "jungle stairs" to Material.JUNGLE_STAIRS,
        "jungle trapdoor" to Material.JUNGLE_TRAPDOOR,
        "jungle wood" to Material.JUNGLE_WOOD,
        "kelp" to Material.KELP,
        "kelp plant" to Material.KELP_PLANT,
        "knowledge book" to Material.KNOWLEDGE_BOOK,
        "ladder" to Material.LADDER,
        "lapis block" to Material.LAPIS_BLOCK,
        "lapis lazuli" to Material.LAPIS_LAZULI,
        "lapis ore" to Material.LAPIS_ORE,
        "large fern" to Material.LARGE_FERN,
        "lava" to Material.LAVA,
        "lava bucket" to Material.LAVA_BUCKET,
        "lead" to Material.LEAD,
        "leather" to Material.LEATHER,
        "leather boots" to Material.LEATHER_BOOTS,
        "leather chestplate" to Material.LEATHER_CHESTPLATE,
        "leather helmet" to Material.LEATHER_HELMET,
        "leather leggings" to Material.LEATHER_LEGGINGS,
        "lever" to Material.LEVER,
        "light blue banner" to Material.LIGHT_BLUE_BANNER,
        "light blue bed" to Material.LIGHT_BLUE_BED,
        "light blue carpet" to Material.LIGHT_BLUE_CARPET,
        "light blue concrete" to Material.LIGHT_BLUE_CONCRETE,
        "light blue concrete powder" to Material.LIGHT_BLUE_CONCRETE_POWDER,
        "light blue dye" to Material.LIGHT_BLUE_DYE,
        "light blue glazed terracotta" to Material.LIGHT_BLUE_GLAZED_TERRACOTTA,
        "light blue shulker box" to Material.LIGHT_BLUE_SHULKER_BOX,
        "light blue stained glass" to Material.LIGHT_BLUE_STAINED_GLASS,
        "light blue stained glass pane" to Material.LIGHT_BLUE_STAINED_GLASS_PANE,
        "light blue terracotta" to Material.LIGHT_BLUE_TERRACOTTA,
        "light blue wall banner" to Material.LIGHT_BLUE_WALL_BANNER,
        "light blue wool" to Material.LIGHT_BLUE_WOOL,
        "light gray banner" to Material.LIGHT_GRAY_BANNER,
        "light gray bed" to Material.LIGHT_GRAY_BED,
        "light gray carpet" to Material.LIGHT_GRAY_CARPET,
        "light gray concrete" to Material.LIGHT_GRAY_CONCRETE,
        "light gray concrete powder" to Material.LIGHT_GRAY_CONCRETE_POWDER,
        "light gray dye" to Material.LIGHT_GRAY_DYE,
        "light gray glazed terracotta" to Material.LIGHT_GRAY_GLAZED_TERRACOTTA,
        "light gray shulker box" to Material.LIGHT_GRAY_SHULKER_BOX,
        "light gray stained glass" to Material.LIGHT_GRAY_STAINED_GLASS,
        "light gray stained glass pane" to Material.LIGHT_GRAY_STAINED_GLASS_PANE,
        "light gray terracotta" to Material.LIGHT_GRAY_TERRACOTTA,
        "light gray wall banner" to Material.LIGHT_GRAY_WALL_BANNER,
        "light gray wool" to Material.LIGHT_GRAY_WOOL,
        "light weighted pressure plate" to Material.LIGHT_WEIGHTED_PRESSURE_PLATE,
        "lilac" to Material.LILAC,
        "lily pad" to Material.LILY_PAD,
        "lime banner" to Material.LIME_BANNER,
        "lime bed" to Material.LIME_BED,
        "lime carpet" to Material.LIME_CARPET,
        "lime concrete" to Material.LIME_CONCRETE,
        "lime concrete powder" to Material.LIME_CONCRETE_POWDER,
        "lime dye" to Material.LIME_DYE,
        "lime glazed terracotta" to Material.LIME_GLAZED_TERRACOTTA,
        "lime shulker box" to Material.LIME_SHULKER_BOX,
        "lime stained glass" to Material.LIME_STAINED_GLASS,
        "lime stained glass pane" to Material.LIME_STAINED_GLASS_PANE,
        "lime terracotta" to Material.LIME_TERRACOTTA,
        "lime wall banner" to Material.LIME_WALL_BANNER,
        "lime wool" to Material.LIME_WOOL,
        "lingering potion" to Material.LINGERING_POTION,
        "llama spawn egg" to Material.LLAMA_SPAWN_EGG,
        "magenta banner" to Material.MAGENTA_BANNER,
        "magenta bed" to Material.MAGENTA_BED,
        "magenta carpet" to Material.MAGENTA_CARPET,
        "magenta concrete" to Material.MAGENTA_CONCRETE,
        "magenta concrete powder" to Material.MAGENTA_CONCRETE_POWDER,
        "magenta dye" to Material.MAGENTA_DYE,
        "magenta glazed terracotta" to Material.MAGENTA_GLAZED_TERRACOTTA,
        "magenta shulker box" to Material.MAGENTA_SHULKER_BOX,
        "magenta stained glass" to Material.MAGENTA_STAINED_GLASS,
        "magenta stained glass pane" to Material.MAGENTA_STAINED_GLASS_PANE,
        "magenta terracotta" to Material.MAGENTA_TERRACOTTA,
        "magenta wall banner" to Material.MAGENTA_WALL_BANNER,
        "magenta wool" to Material.MAGENTA_WOOL,
        "magma block" to Material.MAGMA_BLOCK,
        "magma cream" to Material.MAGMA_CREAM,
        "magma cube spawn egg" to Material.MAGMA_CUBE_SPAWN_EGG,
        "map" to Material.MAP,
        "melon" to Material.MELON,
        "melon seeds" to Material.MELON_SEEDS,
        "melon slice" to Material.MELON_SLICE,
        "melon stem" to Material.MELON_STEM,
        "milk bucket" to Material.MILK_BUCKET,
        "minecart" to Material.MINECART,
        "mooshroom spawn egg" to Material.MOOSHROOM_SPAWN_EGG,
        "mossy cobblestone" to Material.MOSSY_COBBLESTONE,
        "mossy cobblestone wall" to Material.MOSSY_COBBLESTONE_WALL,
        "mossy stone bricks" to Material.MOSSY_STONE_BRICKS,
        "moving piston" to Material.MOVING_PISTON,
        "mule spawn egg" to Material.MULE_SPAWN_EGG,
        "mushroom stem" to Material.MUSHROOM_STEM,
        "mushroom stew" to Material.MUSHROOM_STEW,
        "music disc 11" to Material.MUSIC_DISC_11,
        "music disc 13" to Material.MUSIC_DISC_13,
        "music disc blocks" to Material.MUSIC_DISC_BLOCKS,
        "music disc cat" to Material.MUSIC_DISC_CAT,
        "music disc chirp" to Material.MUSIC_DISC_CHIRP,
        "music disc far" to Material.MUSIC_DISC_FAR,
        "music disc mall" to Material.MUSIC_DISC_MALL,
        "music disc mellohi" to Material.MUSIC_DISC_MELLOHI,
        "music disc stal" to Material.MUSIC_DISC_STAL,
        "music disc strad" to Material.MUSIC_DISC_STRAD,
        "music disc wait" to Material.MUSIC_DISC_WAIT,
        "music disc ward" to Material.MUSIC_DISC_WARD,
        "mutton" to Material.MUTTON,
        "mycelium" to Material.MYCELIUM,
        "name tag" to Material.NAME_TAG,
        "nautilus shell" to Material.NAUTILUS_SHELL,
        "netherrack" to Material.NETHERRACK,
        "nether brick" to Material.NETHER_BRICK,
        "nether bricks" to Material.NETHER_BRICKS,
        "nether brick fence" to Material.NETHER_BRICK_FENCE,
        "nether brick slab" to Material.NETHER_BRICK_SLAB,
        "nether brick stairs" to Material.NETHER_BRICK_STAIRS,
        "nether portal" to Material.NETHER_PORTAL,
        "nether quartz ore" to Material.NETHER_QUARTZ_ORE,
        "nether star" to Material.NETHER_STAR,
        "nether wart" to Material.NETHER_WART,
        "nether wart block" to Material.NETHER_WART_BLOCK,
        "note block" to Material.NOTE_BLOCK,
        "oak boat" to Material.OAK_BOAT,
        "oak button" to Material.OAK_BUTTON,
        "oak door" to Material.OAK_DOOR,
        "oak fence" to Material.OAK_FENCE,
        "oak fence gate" to Material.OAK_FENCE_GATE,
        "oak leaves" to Material.OAK_LEAVES,
        "oak log" to Material.OAK_LOG,
        "oak planks" to Material.OAK_PLANKS,
        "oak pressure plate" to Material.OAK_PRESSURE_PLATE,
        "oak sapling" to Material.OAK_SAPLING,
        "oak slab" to Material.OAK_SLAB,
        "oak stairs" to Material.OAK_STAIRS,
        "oak trapdoor" to Material.OAK_TRAPDOOR,
        "oak wood" to Material.OAK_WOOD,
        "observer" to Material.OBSERVER,
        "obsidian" to Material.OBSIDIAN,
        "ocelot spawn egg" to Material.OCELOT_SPAWN_EGG,
        "orange banner" to Material.ORANGE_BANNER,
        "orange bed" to Material.ORANGE_BED,
        "orange carpet" to Material.ORANGE_CARPET,
        "orange concrete" to Material.ORANGE_CONCRETE,
        "orange concrete powder" to Material.ORANGE_CONCRETE_POWDER,
        "orange dye" to Material.ORANGE_DYE,
        "orange glazed terracotta" to Material.ORANGE_GLAZED_TERRACOTTA,
        "orange shulker box" to Material.ORANGE_SHULKER_BOX,
        "orange stained glass" to Material.ORANGE_STAINED_GLASS,
        "orange stained glass pane" to Material.ORANGE_STAINED_GLASS_PANE,
        "orange terracotta" to Material.ORANGE_TERRACOTTA,
        "orange tulip" to Material.ORANGE_TULIP,
        "orange wall banner" to Material.ORANGE_WALL_BANNER,
        "orange wool" to Material.ORANGE_WOOL,
        "oxeye daisy" to Material.OXEYE_DAISY,
        "packed ice" to Material.PACKED_ICE,
        "painting" to Material.PAINTING,
        "paper" to Material.PAPER,
        "parrot spawn egg" to Material.PARROT_SPAWN_EGG,
        "peony" to Material.PEONY,
        "petrified oak slab" to Material.PETRIFIED_OAK_SLAB,
        "phantom membrane" to Material.PHANTOM_MEMBRANE,
        "phantom spawn egg" to Material.PHANTOM_SPAWN_EGG,
        "pig spawn egg" to Material.PIG_SPAWN_EGG,
        "pink banner" to Material.PINK_BANNER,
        "pink bed" to Material.PINK_BED,
        "pink carpet" to Material.PINK_CARPET,
        "pink concrete" to Material.PINK_CONCRETE,
        "pink concrete powder" to Material.PINK_CONCRETE_POWDER,
        "pink dye" to Material.PINK_DYE,
        "pink glazed terracotta" to Material.PINK_GLAZED_TERRACOTTA,
        "pink shulker box" to Material.PINK_SHULKER_BOX,
        "pink stained glass" to Material.PINK_STAINED_GLASS,
        "pink stained glass pane" to Material.PINK_STAINED_GLASS_PANE,
        "pink terracotta" to Material.PINK_TERRACOTTA,
        "pink tulip" to Material.PINK_TULIP,
        "pink wall banner" to Material.PINK_WALL_BANNER,
        "pink wool" to Material.PINK_WOOL,
        "piston" to Material.PISTON,
        "piston head" to Material.PISTON_HEAD,
        "player head" to Material.PLAYER_HEAD,
        "player wall head" to Material.PLAYER_WALL_HEAD,
        "podzol" to Material.PODZOL,
        "poisonous potato" to Material.POISONOUS_POTATO,
        "polar bear spawn egg" to Material.POLAR_BEAR_SPAWN_EGG,
        "polished andesite" to Material.POLISHED_ANDESITE,
        "polished diorite" to Material.POLISHED_DIORITE,
        "polished granite" to Material.POLISHED_GRANITE,
        "popped chorus fruit" to Material.POPPED_CHORUS_FRUIT,
        "poppy" to Material.POPPY,
        "porkchop" to Material.PORKCHOP,
        "potato" to Material.POTATO,
        "potatoes" to Material.POTATOES,
        "potion" to Material.POTION,
        "potted acacia sapling" to Material.POTTED_ACACIA_SAPLING,
        "potted allium" to Material.POTTED_ALLIUM,
        "potted azure bluet" to Material.POTTED_AZURE_BLUET,
        "potted birch sapling" to Material.POTTED_BIRCH_SAPLING,
        "potted blue orchid" to Material.POTTED_BLUE_ORCHID,
        "potted brown mushroom" to Material.POTTED_BROWN_MUSHROOM,
        "potted cactus" to Material.POTTED_CACTUS,
        "potted dandelion" to Material.POTTED_DANDELION,
        "potted dark oak sapling" to Material.POTTED_DARK_OAK_SAPLING,
        "potted dead bush" to Material.POTTED_DEAD_BUSH,
        "potted fern" to Material.POTTED_FERN,
        "potted jungle sapling" to Material.POTTED_JUNGLE_SAPLING,
        "potted oak sapling" to Material.POTTED_OAK_SAPLING,
        "potted orange tulip" to Material.POTTED_ORANGE_TULIP,
        "potted oxeye daisy" to Material.POTTED_OXEYE_DAISY,
        "potted pink tulip" to Material.POTTED_PINK_TULIP,
        "potted poppy" to Material.POTTED_POPPY,
        "potted red mushroom" to Material.POTTED_RED_MUSHROOM,
        "potted red tulip" to Material.POTTED_RED_TULIP,
        "potted spruce sapling" to Material.POTTED_SPRUCE_SAPLING,
        "potted white tulip" to Material.POTTED_WHITE_TULIP,
        "powered rail" to Material.POWERED_RAIL,
        "prismarine" to Material.PRISMARINE,
        "prismarine bricks" to Material.PRISMARINE_BRICKS,
        "prismarine brick slab" to Material.PRISMARINE_BRICK_SLAB,
        "prismarine brick stairs" to Material.PRISMARINE_BRICK_STAIRS,
        "prismarine crystals" to Material.PRISMARINE_CRYSTALS,
        "prismarine shard" to Material.PRISMARINE_SHARD,
        "prismarine slab" to Material.PRISMARINE_SLAB,
        "prismarine stairs" to Material.PRISMARINE_STAIRS,
        "pufferfish" to Material.PUFFERFISH,
        "pufferfish bucket" to Material.PUFFERFISH_BUCKET,
        "pufferfish spawn egg" to Material.PUFFERFISH_SPAWN_EGG,
        "pumpkin" to Material.PUMPKIN,
        "pumpkin pie" to Material.PUMPKIN_PIE,
        "pumpkin seeds" to Material.PUMPKIN_SEEDS,
        "pumpkin stem" to Material.PUMPKIN_STEM,
        "purple banner" to Material.PURPLE_BANNER,
        "purple bed" to Material.PURPLE_BED,
        "purple carpet" to Material.PURPLE_CARPET,
        "purple concrete" to Material.PURPLE_CONCRETE,
        "purple concrete powder" to Material.PURPLE_CONCRETE_POWDER,
        "purple dye" to Material.PURPLE_DYE,
        "purple glazed terracotta" to Material.PURPLE_GLAZED_TERRACOTTA,
        "purple shulker box" to Material.PURPLE_SHULKER_BOX,
        "purple stained glass" to Material.PURPLE_STAINED_GLASS,
        "purple stained glass pane" to Material.PURPLE_STAINED_GLASS_PANE,
        "purple terracotta" to Material.PURPLE_TERRACOTTA,
        "purple wall banner" to Material.PURPLE_WALL_BANNER,
        "purple wool" to Material.PURPLE_WOOL,
        "purpur block" to Material.PURPUR_BLOCK,
        "purpur pillar" to Material.PURPUR_PILLAR,
        "purpur slab" to Material.PURPUR_SLAB,
        "purpur stairs" to Material.PURPUR_STAIRS,
        "quartz" to Material.QUARTZ,
        "quartz block" to Material.QUARTZ_BLOCK,
        "quartz pillar" to Material.QUARTZ_PILLAR,
        "quartz slab" to Material.QUARTZ_SLAB,
        "quartz stairs" to Material.QUARTZ_STAIRS,
        "rabbit" to Material.RABBIT,
        "rabbit foot" to Material.RABBIT_FOOT,
        "rabbit hide" to Material.RABBIT_HIDE,
        "rabbit spawn egg" to Material.RABBIT_SPAWN_EGG,
        "rabbit stew" to Material.RABBIT_STEW,
        "rail" to Material.RAIL,
        "redstone" to Material.REDSTONE,
        "redstone block" to Material.REDSTONE_BLOCK,
        "redstone lamp" to Material.REDSTONE_LAMP,
        "redstone ore" to Material.REDSTONE_ORE,
        "redstone torch" to Material.REDSTONE_TORCH,
        "redstone wall torch" to Material.REDSTONE_WALL_TORCH,
        "redstone wire" to Material.REDSTONE_WIRE,
        "red banner" to Material.RED_BANNER,
        "red bed" to Material.RED_BED,
        "red carpet" to Material.RED_CARPET,
        "red concrete" to Material.RED_CONCRETE,
        "red concrete powder" to Material.RED_CONCRETE_POWDER,
        "red glazed terracotta" to Material.RED_GLAZED_TERRACOTTA,
        "red mushroom" to Material.RED_MUSHROOM,
        "red mushroom block" to Material.RED_MUSHROOM_BLOCK,
        "red nether bricks" to Material.RED_NETHER_BRICKS,
        "red sand" to Material.RED_SAND,
        "red sandstone" to Material.RED_SANDSTONE,
        "red sandstone slab" to Material.RED_SANDSTONE_SLAB,
        "red sandstone stairs" to Material.RED_SANDSTONE_STAIRS,
        "red shulker box" to Material.RED_SHULKER_BOX,
        "red stained glass" to Material.RED_STAINED_GLASS,
        "red stained glass pane" to Material.RED_STAINED_GLASS_PANE,
        "red terracotta" to Material.RED_TERRACOTTA,
        "red tulip" to Material.RED_TULIP,
        "red wall banner" to Material.RED_WALL_BANNER,
        "red wool" to Material.RED_WOOL,
        "repeater" to Material.REPEATER,
        "repeating command block" to Material.REPEATING_COMMAND_BLOCK,
        "rose bush" to Material.ROSE_BUSH,
        "rose red" to Material.ROSE_RED,
        "rotten flesh" to Material.ROTTEN_FLESH,
        "saddle" to Material.SADDLE,
        "salmon" to Material.SALMON,
        "salmon bucket" to Material.SALMON_BUCKET,
        "salmon spawn egg" to Material.SALMON_SPAWN_EGG,
        "sand" to Material.SAND,
        "sandstone" to Material.SANDSTONE,
        "sandstone slab" to Material.SANDSTONE_SLAB,
        "sandstone stairs" to Material.SANDSTONE_STAIRS,
        "scute" to Material.SCUTE,
        "seagrass" to Material.SEAGRASS,
        "sea lantern" to Material.SEA_LANTERN,
        "sea pickle" to Material.SEA_PICKLE,
        "shears" to Material.SHEARS,
        "sheep spawn egg" to Material.SHEEP_SPAWN_EGG,
        "shield" to Material.SHIELD,
        "shulker box" to Material.SHULKER_BOX,
        "shulker shell" to Material.SHULKER_SHELL,
        "shulker spawn egg" to Material.SHULKER_SPAWN_EGG,
        "sign" to Material.SIGN,
        "silverfish spawn egg" to Material.SILVERFISH_SPAWN_EGG,
        "skeleton horse spawn egg" to Material.SKELETON_HORSE_SPAWN_EGG,
        "skeleton skull" to Material.SKELETON_SKULL,
        "skeleton spawn egg" to Material.SKELETON_SPAWN_EGG,
        "skeleton wall skull" to Material.SKELETON_WALL_SKULL,
        "slime ball" to Material.SLIME_BALL,
        "slime block" to Material.SLIME_BLOCK,
        "slime spawn egg" to Material.SLIME_SPAWN_EGG,
        "smooth quartz" to Material.SMOOTH_QUARTZ,
        "smooth red sandstone" to Material.SMOOTH_RED_SANDSTONE,
        "smooth sandstone" to Material.SMOOTH_SANDSTONE,
        "smooth stone" to Material.SMOOTH_STONE,
        "snow" to Material.SNOW,
        "snowball" to Material.SNOWBALL,
        "snow block" to Material.SNOW_BLOCK,
        "soul sand" to Material.SOUL_SAND,
        "spawner" to Material.SPAWNER,
        "spectral arrow" to Material.SPECTRAL_ARROW,
        "spider eye" to Material.SPIDER_EYE,
        "spider spawn egg" to Material.SPIDER_SPAWN_EGG,
        "splash potion" to Material.SPLASH_POTION,
        "sponge" to Material.SPONGE,
        "spruce boat" to Material.SPRUCE_BOAT,
        "spruce button" to Material.SPRUCE_BUTTON,
        "spruce door" to Material.SPRUCE_DOOR,
        "spruce fence" to Material.SPRUCE_FENCE,
        "spruce fence gate" to Material.SPRUCE_FENCE_GATE,
        "spruce leaves" to Material.SPRUCE_LEAVES,
        "spruce log" to Material.SPRUCE_LOG,
        "spruce planks" to Material.SPRUCE_PLANKS,
        "spruce pressure plate" to Material.SPRUCE_PRESSURE_PLATE,
        "spruce sapling" to Material.SPRUCE_SAPLING,
        "spruce slab" to Material.SPRUCE_SLAB,
        "spruce stairs" to Material.SPRUCE_STAIRS,
        "spruce trapdoor" to Material.SPRUCE_TRAPDOOR,
        "spruce wood" to Material.SPRUCE_WOOD,
        "squid spawn egg" to Material.SQUID_SPAWN_EGG,
        "stick" to Material.STICK,
        "sticky piston" to Material.STICKY_PISTON,
        "stone" to Material.STONE,
        "stone axe" to Material.STONE_AXE,
        "stone bricks" to Material.STONE_BRICKS,
        "stone brick slab" to Material.STONE_BRICK_SLAB,
        "stone brick stairs" to Material.STONE_BRICK_STAIRS,
        "stone button" to Material.STONE_BUTTON,
        "stone hoe" to Material.STONE_HOE,
        "stone pickaxe" to Material.STONE_PICKAXE,
        "stone pressure plate" to Material.STONE_PRESSURE_PLATE,
        "stone shovel" to Material.STONE_SHOVEL,
        "stone slab" to Material.STONE_SLAB,
        "stone sword" to Material.STONE_SWORD,
        "stray spawn egg" to Material.STRAY_SPAWN_EGG,
        "string" to Material.STRING,
        "stripped acacia log" to Material.STRIPPED_ACACIA_LOG,
        "stripped acacia wood" to Material.STRIPPED_ACACIA_WOOD,
        "stripped birch log" to Material.STRIPPED_BIRCH_LOG,
        "stripped birch wood" to Material.STRIPPED_BIRCH_WOOD,
        "stripped dark oak log" to Material.STRIPPED_DARK_OAK_LOG,
        "stripped dark oak wood" to Material.STRIPPED_DARK_OAK_WOOD,
        "stripped jungle log" to Material.STRIPPED_JUNGLE_LOG,
        "stripped jungle wood" to Material.STRIPPED_JUNGLE_WOOD,
        "stripped oak log" to Material.STRIPPED_OAK_LOG,
        "stripped oak wood" to Material.STRIPPED_OAK_WOOD,
        "stripped spruce log" to Material.STRIPPED_SPRUCE_LOG,
        "stripped spruce wood" to Material.STRIPPED_SPRUCE_WOOD,
        "structure block" to Material.STRUCTURE_BLOCK,
        "structure void" to Material.STRUCTURE_VOID,
        "sugar" to Material.SUGAR,
        "sugar cane" to Material.SUGAR_CANE,
        "sunflower" to Material.SUNFLOWER,
        "tall grass" to Material.TALL_GRASS,
        "tall seagrass" to Material.TALL_SEAGRASS,
        "terracotta" to Material.TERRACOTTA,
        "tipped arrow" to Material.TIPPED_ARROW,
        "tnt" to Material.TNT,
        "tnt minecart" to Material.TNT_MINECART,
        "torch" to Material.TORCH,
        "totem of undying" to Material.TOTEM_OF_UNDYING,
        "trapped chest" to Material.TRAPPED_CHEST,
        "trident" to Material.TRIDENT,
        "tripwire" to Material.TRIPWIRE,
        "tripwire hook" to Material.TRIPWIRE_HOOK,
        "tropical fish" to Material.TROPICAL_FISH,
        "tropical fish bucket" to Material.TROPICAL_FISH_BUCKET,
        "tropical fish spawn egg" to Material.TROPICAL_FISH_SPAWN_EGG,
        "tube coral" to Material.TUBE_CORAL,
        "tube coral block" to Material.TUBE_CORAL_BLOCK,
        "tube coral fan" to Material.TUBE_CORAL_FAN,
        "tube coral wall fan" to Material.TUBE_CORAL_WALL_FAN,
        "turtle egg" to Material.TURTLE_EGG,
        "turtle helmet" to Material.TURTLE_HELMET,
        "turtle spawn egg" to Material.TURTLE_SPAWN_EGG,
        "vex spawn egg" to Material.VEX_SPAWN_EGG,
        "villager spawn egg" to Material.VILLAGER_SPAWN_EGG,
        "vindicator spawn egg" to Material.VINDICATOR_SPAWN_EGG,
        "vine" to Material.VINE,
        "void air" to Material.VOID_AIR,
        "wall sign" to Material.WALL_SIGN,
        "wall torch" to Material.WALL_TORCH,
        "water" to Material.WATER,
        "water bucket" to Material.WATER_BUCKET,
        "wet sponge" to Material.WET_SPONGE,
        "wheat" to Material.WHEAT,
        "wheat seeds" to Material.WHEAT_SEEDS,
        "white banner" to Material.WHITE_BANNER,
        "white bed" to Material.WHITE_BED,
        "white carpet" to Material.WHITE_CARPET,
        "white concrete" to Material.WHITE_CONCRETE,
        "white concrete powder" to Material.WHITE_CONCRETE_POWDER,
        "white glazed terracotta" to Material.WHITE_GLAZED_TERRACOTTA,
        "white shulker box" to Material.WHITE_SHULKER_BOX,
        "white stained glass" to Material.WHITE_STAINED_GLASS,
        "white stained glass pane" to Material.WHITE_STAINED_GLASS_PANE,
        "white terracotta" to Material.WHITE_TERRACOTTA,
        "white tulip" to Material.WHITE_TULIP,
        "white wall banner" to Material.WHITE_WALL_BANNER,
        "white wool" to Material.WHITE_WOOL,
        "witch spawn egg" to Material.WITCH_SPAWN_EGG,
        "wither skeleton skull" to Material.WITHER_SKELETON_SKULL,
        "wither skeleton spawn egg" to Material.WITHER_SKELETON_SPAWN_EGG,
        "wither skeleton wall skull" to Material.WITHER_SKELETON_WALL_SKULL,
        "wolf spawn egg" to Material.WOLF_SPAWN_EGG,
        "wooden axe" to Material.WOODEN_AXE,
        "wooden hoe" to Material.WOODEN_HOE,
        "wooden pickaxe" to Material.WOODEN_PICKAXE,
        "wooden shovel" to Material.WOODEN_SHOVEL,
        "wooden sword" to Material.WOODEN_SWORD,
        "writable book" to Material.WRITABLE_BOOK,
        "written book" to Material.WRITTEN_BOOK,
        "yellow banner" to Material.YELLOW_BANNER,
        "yellow bed" to Material.YELLOW_BED,
        "yellow carpet" to Material.YELLOW_CARPET,
        "yellow concrete" to Material.YELLOW_CONCRETE,
        "yellow concrete powder" to Material.YELLOW_CONCRETE_POWDER,
        "yellow glazed terracotta" to Material.YELLOW_GLAZED_TERRACOTTA,
        "yellow shulker box" to Material.YELLOW_SHULKER_BOX,
        "yellow stained glass" to Material.YELLOW_STAINED_GLASS,
        "yellow stained glass pane" to Material.YELLOW_STAINED_GLASS_PANE,
        "yellow terracotta" to Material.YELLOW_TERRACOTTA,
        "yellow wall banner" to Material.YELLOW_WALL_BANNER,
        "yellow wool" to Material.YELLOW_WOOL,
        "zombie head" to Material.ZOMBIE_HEAD,
        "zombie horse spawn egg" to Material.ZOMBIE_HORSE_SPAWN_EGG,
        "zombie pigman spawn egg" to Material.ZOMBIE_PIGMAN_SPAWN_EGG,
        "zombie spawn egg" to Material.ZOMBIE_SPAWN_EGG,
        "zombie villager spawn egg" to Material.ZOMBIE_VILLAGER_SPAWN_EGG,
        "zombie wall head" to Material.ZOMBIE_WALL_HEAD
    )
}